% Mass Balance
function check = mass_balance(C,P)
conc = {'c_ATP', 'c_Bicarbonate', 'c_AcCoA', 'c_SucCoA', 'c_HexCoA', 'c_OcCoA', 'c_DecCoA', 'c_LauCoA', 'c_EthCoA', 'c_PalCoA', 'c_OcDecCoA', 'c_ACP', 'c_NADPH', 'c_NADP', 'c_NADH', 'c_NAD', 'c_ADP',...
    'c_MalCoA', 'c_CoA', 'c_MalACP', 'c_CO2', 'c_C4_BKeACP', 'c_C6_BKeACP', 'c_C8_BKeACP', 'c_C10_BKeACP', 'c_C12_BKeACP', 'c_C14_BKeACP', 'c_C16_BKeACP', 'c_C18_BKeACP',...
    'c_C20_BKeACP', 'c_C12_BKeACP_un', 'c_C14_BKeACP_un', 'c_C16_BKeACP_un', 'c_C18_BKeACP_un', 'c_C20_BKeACP_un', 'c_C4_BHyAcACP', 'c_C6_BHyAcACP', 'c_C8_BHyAcACP',...
    'c_C10_BHyAcACP', 'c_C12_BHyAcACP', 'c_C14_BHyAcACP', 'c_C16_BHyAcACP', 'c_C18_BHyAcACP', 'c_C20_BHyAcACP', 'c_C12_BHyAcACP_un', 'c_C14_BHyAcACP_un',...
    'c_C16_BHyAcACP_un', 'c_C18_BHyAcACP_un', 'c_C20_BHyAcACP_un', 'c_C4_EnAcACP', 'c_C6_EnAcACP', 'c_C8_EnAcACP', 'c_C10_EnAcACP', 'c_C12_EnAcACP', 'c_C14_EnAcACP',...
    'c_C16_EnAcACP', 'c_C18_EnAcACP', 'c_C20_EnAcACP', 'c_C10_cis3EnAcACP', 'c_C12_EnAcACP_un', 'c_C14_EnAcACP_un', 'c_C16_EnAcACP_un', 'c_C18_EnAcACP_un',...
    'c_C20_EnAcACP_un', 'c_C4_AcACP', 'c_C6_AcACP', 'c_C8_AcACP', 'c_C10_AcACP', 'c_C12_AcACP', 'c_C14_AcACP', 'c_C16_AcACP', 'c_C18_AcACP', 'c_C20_AcACP',...
    'c_C12_AcACP_un', 'c_C14_AcACP_un', 'c_C16_AcACP_un', 'c_C18_AcACP_un', 'c_C20_AcACP_un', 'c_C4_FA', 'c_C6_FA', 'c_C8_FA', 'c_C10_FA', 'c_C12_FA', 'c_C14_FA',...
    'c_C16_FA', 'c_C18_FA', 'c_C20_FA', 'c_C12_FA_un', 'c_C14_FA_un', 'c_C16_FA_un', 'c_C18_FA_un', 'c_C20_FA_un', 'c_ACC_s1', 'c_ACC_s2', 'c_ACC_s3', 'c_ACC_s4', 'c_FabD_MalCoA',...
    'c_FabD_Act', 'c_FabD_Act_ACP', 'c_C2_FabH_CoA', 'c_C4_FabH_CoA', 'c_C6_FabH_CoA', 'c_C8_FabH_CoA', 'c_C10_FabH_CoA', 'c_C12_FabH_CoA', 'c_C14_FabH_CoA',...
    'c_C16_FabH_CoA', 'c_C18_FabH_CoA', 'c_C2_FabH_Act', 'c_C4_FabH_Act', 'c_C6_FabH_Act', 'c_C8_FabH_Act', 'c_C10_FabH_Act', 'c_C12_FabH_Act', 'c_C14_FabH_Act',...
    'c_C16_FabH_Act', 'c_C18_FabH_Act', 'c_C2_FabH_Act_MalACP', 'c_C4_FabH_Act_MalACP', 'c_C6_FabH_Act_MalACP', 'c_C8_FabH_Act_MalACP', 'c_C10_FabH_Act_MalACP',...
    'c_C12_FabH_Act_MalACP', 'c_C14_FabH_Act_MalACP', 'c_C16_FabH_Act_MalACP', 'c_C18_FabH_Act_MalACP', 'c_FabG_NADPH', 'c_C4_FabG_NADPH_BKeACP',...
    'c_C6_FabG_NADPH_BKeACP', 'c_C8_FabG_NADPH_BKeACP', 'c_C10_FabG_NADPH_BKeACP', 'c_C12_FabG_NADPH_BKeACP', 'c_C14_FabG_NADPH_BKeACP',...
    'c_C16_FabG_NADPH_BKeACP', 'c_C18_FabG_NADPH_BKeACP', 'c_C20_FabG_NADPH_BKeACP', 'c_C12_FabG_NADPH_BKeACP_un', 'c_C14_FabG_NADPH_BKeACP_un',...
    'c_C16_FabG_NADPH_BKeACP_un', 'c_C18_FabG_NADPH_BKeACP_un', 'c_C20_FabG_NADPH_BKeACP_un', 'c_C4_FabZ_BHyAcACP', 'c_C6_FabZ_BHyAcACP',...
    'c_C8_FabZ_BHyAcACP', 'c_C10_FabZ_BHyAcACP', 'c_C12_FabZ_BHyAcACP', 'c_C14_FabZ_BHyAcACP', 'c_C16_FabZ_BHyAcACP', 'c_C18_FabZ_BHyAcACP',...
    'c_C20_FabZ_BHyAcACP', 'c_C12_FabZ_BHyAcACP_un', 'c_C14_FabZ_BHyAcACP_un', 'c_C16_FabZ_BHyAcACP_un', 'c_C18_FabZ_BHyAcACP_un', 'c_C20_FabZ_BHyAcACP_un',...
    'c_C4_FabZ_EnAcACP', 'c_C6_FabZ_EnAcACP', 'c_C8_FabZ_EnAcACP', 'c_C10_FabZ_EnAcACP', 'c_C12_FabZ_EnAcACP', 'c_C14_FabZ_EnAcACP', 'c_C16_FabZ_EnAcACP',...
    'c_C18_FabZ_EnAcACP', 'c_C20_FabZ_EnAcACP', 'c_C12_FabZ_EnAcACP_un', 'c_C14_FabZ_EnAcACP_un', 'c_C16_FabZ_EnAcACP_un', 'c_C18_FabZ_EnAcACP_un',...
    'c_C20_FabZ_EnAcACP_un', 'c_C4_FabA_BHyAcACP', 'c_C6_FabA_BHyAcACP', 'c_C8_FabA_BHyAcACP', 'c_C10_FabA_BHyAcACP', 'c_C12_FabA_BHyAcACP',...
    'c_C14_FabA_BHyAcACP', 'c_C16_FabA_BHyAcACP', 'c_C18_FabA_BHyAcACP', 'c_C20_FabA_BHyAcACP', 'c_C12_FabA_BHyAcACP_un', 'c_C14_FabA_BHyAcACP_un',...
    'c_C16_FabA_BHyAcACP_un', 'c_C18_FabA_BHyAcACP_un', 'c_C20_FabA_BHyAcACP_un', 'c_C4_FabA_EnAcACP', 'c_C6_FabA_EnAcACP', 'c_C8_FabA_EnAcACP', 'c_C10_FabA_EnAcACP',...
    'c_C12_FabA_EnAcACP', 'c_C14_FabA_EnAcACP', 'c_C16_FabA_EnAcACP', 'c_C18_FabA_EnAcACP', 'c_C20_FabA_EnAcACP', 'c_C10_FabA_cis3EnAcACP', 'c_C12_FabA_EnAcACP_un',...
    'c_C14_FabA_EnAcACP_un', 'c_C16_FabA_EnAcACP_un', 'c_C18_FabA_EnAcACP_un', 'c_C20_FabA_EnAcACP_un', 'c_FabI_NADH', 'c_C4_FabI_NADH_EnAcACP',...
    'c_C6_FabI_NADH_EnAcACP', 'c_C8_FabI_NADH_EnAcACP', 'c_C10_FabI_NADH_EnAcACP', 'c_C12_FabI_NADH_EnAcACP', 'c_C14_FabI_NADH_EnAcACP',...
    'c_C16_FabI_NADH_EnAcACP', 'c_C18_FabI_NADH_EnAcACP', 'c_C20_FabI_NADH_EnAcACP', 'c_C12_FabI_NADH_EnAcACP_un', 'c_C14_FabI_NADH_EnAcACP_un',...
    'c_C16_FabI_NADH_EnAcACP_un', 'c_C18_FabI_NADH_EnAcACP_un', 'c_C20_FabI_NADH_EnAcACP_un', 'c_C4_TesA_AcACP', 'c_C6_TesA_AcACP', 'c_C8_TesA_AcACP',...
    'c_C10_TesA_AcACP', 'c_C12_TesA_AcACP', 'c_C14_TesA_AcACP', 'c_C16_TesA_AcACP', 'c_C18_TesA_AcACP', 'c_C20_TesA_AcACP', 'c_C12_TesA_AcACP_un', 'c_C14_TesA_AcACP_un',...
    'c_C16_TesA_AcACP_un', 'c_C18_TesA_AcACP_un', 'c_C20_TesA_AcACP_un', 'c_C4_FabF_AcACP', 'c_C6_FabF_AcACP', 'c_C8_FabF_AcACP', 'c_C10_FabF_AcACP',...
    'c_C12_FabF_AcACP', 'c_C14_FabF_AcACP', 'c_C16_FabF_AcACP', 'c_C18_FabF_AcACP', 'c_C12_FabF_AcACP_un', 'c_C14_FabF_AcACP_un', 'c_C16_FabF_AcACP_un',...
    'c_C18_FabF_AcACP_un', 'c_C4_FabF_Act', 'c_C6_FabF_Act', 'c_C8_FabF_Act', 'c_C10_FabF_Act', 'c_C12_FabF_Act', 'c_C14_FabF_Act', 'c_C16_FabF_Act', 'c_C18_FabF_Act',...
    'c_C12_FabF_Act_un', 'c_C14_FabF_Act_un', 'c_C16_FabF_Act_un', 'c_C18_FabF_Act_un', 'c_C4_FabF_Act_MalACP', 'c_C6_FabF_Act_MalACP', 'c_C8_FabF_Act_MalACP',...
    'c_C10_FabF_Act_MalACP', 'c_C12_FabF_Act_MalACP', 'c_C14_FabF_Act_MalACP', 'c_C16_FabF_Act_MalACP', 'c_C18_FabF_Act_MalACP', 'c_C12_FabF_Act_MalACP_un',...
    'c_C14_FabF_Act_MalACP_un', 'c_C16_FabF_Act_MalACP_un', 'c_C18_FabF_Act_MalACP_un', 'c_C4_FabB_AcACP', 'c_C6_FabB_AcACP', 'c_C8_FabB_AcACP', 'c_C10_FabB_AcACP',...
    'c_C12_FabB_AcACP', 'c_C14_FabB_AcACP', 'c_C16_FabB_AcACP', 'c_C18_FabB_AcACP', 'c_C12_FabB_AcACP_un', 'c_C14_FabB_AcACP_un', 'c_C16_FabB_AcACP_un',...
    'c_C18_FabB_AcACP_un', 'c_C4_FabB_Act', 'c_C6_FabB_Act', 'c_C8_FabB_Act', 'c_C10_FabB_Act', 'c_C12_FabB_Act', 'c_C14_FabB_Act', 'c_C16_FabB_Act', 'c_C18_FabB_Act',...
    'c_C12_FabB_Act_un', 'c_C14_FabB_Act_un', 'c_C16_FabB_Act_un', 'c_C18_FabB_Act_un', 'c_C4_FabB_Act_MalACP', 'c_C6_FabB_Act_MalACP', 'c_C8_FabB_Act_MalACP',...
    'c_C10_FabB_Act_MalACP', 'c_C12_FabB_Act_MalACP', 'c_C14_FabB_Act_MalACP', 'c_C16_FabB_Act_MalACP', 'c_C18_FabB_Act_MalACP', 'c_C12_FabB_Act_MalACP_un',...
    'c_C14_FabB_Act_MalACP_un', 'c_C16_FabB_Act_MalACP_un', 'c_C18_FabB_Act_MalACP_un', 'c_C10_FabB_cis3EnAcACP', 'c_C10_FabB_Act_cis3', 'c_C10_FabB_Act_cis3MalACP',...
    'c_C4_FabH_AcACP', 'c_C6_FabH_AcACP', 'c_C8_FabH_AcACP', 'c_C10_FabH_AcACP', 'c_C12_FabH_AcACP', 'c_C14_FabH_AcACP', 'c_C16_FabH_AcACP', 'c_C18_FabH_AcACP',...
    'c_C20_FabH_AcACP', 'c_C12_FabH_AcACP_un', 'c_C14_FabH_AcACP_un', 'c_C16_FabH_AcACP_un', 'c_C18_FabH_AcACP_un', 'c_C20_FabH_AcACP_un', 'c_C4_FabH_Act_AcACP',...
    'c_C6_FabH_Act_AcACP', 'c_C8_FabH_Act_AcACP', 'c_C10_FabH_Act_AcACP', 'c_C12_FabH_Act_AcACP', 'c_C14_FabH_Act_AcACP', 'c_C16_FabH_Act_AcACP', 'c_C18_FabH_Act_AcACP',...
    'c_C20_FabH_Act_AcACP', 'c_C12_FabH_Act_AcACP_un', 'c_C14_FabH_Act_AcACP_un', 'c_C16_FabH_Act_AcACP_un', 'c_C18_FabH_Act_AcACP_un', 'c_C20_FabH_Act_AcACP_un',...
    'c_TesA_ACP', 'c_FabH_ACP', 'c_FabG_ACP', 'c_FabZ_ACP', 'c_FabI_ACP', 'c_FabF_ACP', 'c_FabA_ACP', 'c_FabB_ACP', 'c_FabB_AcCoA', 'c_C2_FabB_Act', 'c_C2_FabB_Act_MalACP', 'c_FabF_AcCoA',...
    'c_C2_FabF_Act', 'c_C2_FabF_Act_MalACP', 'c_FabB_MalACP', 'c_AcACP', 'c_C2_FabB_AcACP', 'c_FabF_MalACP', 'c_C2_FabF_AcACP'};

% Assign values to each variable
for var = 1:numel(conc)
    % Get the variable name
    var_name = conc{var};
    
    % Get the corresponding index for the value from vector c
    index = C(var);
    
    % Assign the value to the variable in the workspace
    eval([var_name ' = ' num2str(index) ';']);
end

% ACC
c_ACC = P.ACCtot - c_ACC_s1 - c_ACC_s2 - c_ACC_s3 - c_ACC_s4;

% FabD
c_FabD = P.FabDtot - c_FabD_MalCoA - c_FabD_Act - c_FabD_Act_ACP;

% FabH %changed
c_FabH = P.FabHtot - c_FabH_ACP...
    - c_C2_FabH_CoA - c_C4_FabH_CoA - c_C6_FabH_CoA - c_C8_FabH_CoA - c_C10_FabH_CoA - c_C12_FabH_CoA - c_C14_FabH_CoA - c_C16_FabH_CoA - c_C18_FabH_CoA...
    - c_C2_FabH_Act - c_C4_FabH_Act - c_C6_FabH_Act - c_C8_FabH_Act - c_C10_FabH_Act - c_C12_FabH_Act - c_C14_FabH_Act - c_C16_FabH_Act - c_C18_FabH_Act...
    - c_C2_FabH_Act_MalACP - c_C4_FabH_Act_MalACP - c_C6_FabH_Act_MalACP - c_C8_FabH_Act_MalACP - c_C10_FabH_Act_MalACP - c_C12_FabH_Act_MalACP - c_C14_FabH_Act_MalACP - c_C16_FabH_Act_MalACP - c_C18_FabH_Act_MalACP...
    - c_C4_FabH_AcACP - c_C6_FabH_AcACP - c_C8_FabH_AcACP - c_C10_FabH_AcACP - c_C12_FabH_AcACP - c_C14_FabH_AcACP - c_C16_FabH_AcACP - c_C18_FabH_AcACP - c_C20_FabH_AcACP...
    - c_C12_FabH_AcACP_un - c_C14_FabH_AcACP_un - c_C16_FabH_AcACP_un - c_C18_FabH_AcACP_un - c_C20_FabH_AcACP_un...
    - c_C4_FabH_Act_AcACP - c_C6_FabH_Act_AcACP - c_C8_FabH_Act_AcACP - c_C10_FabH_Act_AcACP - c_C12_FabH_Act_AcACP - c_C14_FabH_Act_AcACP - c_C16_FabH_Act_AcACP - c_C18_FabH_Act_AcACP - c_C20_FabH_Act_AcACP...
    - c_C12_FabH_Act_AcACP_un - c_C14_FabH_Act_AcACP_un - c_C16_FabH_Act_AcACP_un - c_C18_FabH_Act_AcACP_un - c_C20_FabH_Act_AcACP_un;

% FabG
c_FabG = P.FabGtot - c_FabG_NADPH...
    - c_C4_FabG_NADPH_BKeACP - c_C6_FabG_NADPH_BKeACP - c_C8_FabG_NADPH_BKeACP - c_C10_FabG_NADPH_BKeACP - c_C12_FabG_NADPH_BKeACP - c_C14_FabG_NADPH_BKeACP - c_C16_FabG_NADPH_BKeACP - c_C18_FabG_NADPH_BKeACP - c_C20_FabG_NADPH_BKeACP...
    - c_C12_FabG_NADPH_BKeACP_un - c_C14_FabG_NADPH_BKeACP_un - c_C16_FabG_NADPH_BKeACP_un - c_C18_FabG_NADPH_BKeACP_un - c_C20_FabG_NADPH_BKeACP_un - c_FabG_ACP;

% FabZ
c_FabZ = P.FabZtot - c_FabZ_ACP...
    - c_C4_FabZ_BHyAcACP - c_C6_FabZ_BHyAcACP - c_C8_FabZ_BHyAcACP - c_C10_FabZ_BHyAcACP - c_C12_FabZ_BHyAcACP - c_C14_FabZ_BHyAcACP - c_C16_FabZ_BHyAcACP - c_C18_FabZ_BHyAcACP - c_C20_FabZ_BHyAcACP...
    - c_C12_FabZ_BHyAcACP_un - c_C14_FabZ_BHyAcACP_un - c_C16_FabZ_BHyAcACP_un - c_C18_FabZ_BHyAcACP_un - c_C20_FabZ_BHyAcACP_un...
    - c_C4_FabZ_EnAcACP - c_C6_FabZ_EnAcACP - c_C8_FabZ_EnAcACP - c_C10_FabZ_EnAcACP - c_C12_FabZ_EnAcACP - c_C14_FabZ_EnAcACP - c_C16_FabZ_EnAcACP - c_C18_FabZ_EnAcACP - c_C20_FabZ_EnAcACP...
    - c_C12_FabZ_EnAcACP_un - c_C14_FabZ_EnAcACP_un - c_C16_FabZ_EnAcACP_un - c_C18_FabZ_EnAcACP_un - c_C20_FabZ_EnAcACP_un;

% FabI
c_FabI = P.FabItot - c_FabI_NADH...
    - c_C4_FabI_NADH_EnAcACP - c_C6_FabI_NADH_EnAcACP - c_C8_FabI_NADH_EnAcACP - c_C10_FabI_NADH_EnAcACP - c_C12_FabI_NADH_EnAcACP - c_C14_FabI_NADH_EnAcACP - c_C16_FabI_NADH_EnAcACP - c_C18_FabI_NADH_EnAcACP - c_C20_FabI_NADH_EnAcACP...
    - c_C12_FabI_NADH_EnAcACP_un - c_C14_FabI_NADH_EnAcACP_un - c_C16_FabI_NADH_EnAcACP_un - c_C18_FabI_NADH_EnAcACP_un - c_C20_FabI_NADH_EnAcACP_un - c_FabI_ACP;

% TesA
c_TesA = P.TesAtot- c_TesA_ACP...
    - c_C4_TesA_AcACP - c_C6_TesA_AcACP - c_C8_TesA_AcACP - c_C10_TesA_AcACP - c_C12_TesA_AcACP - c_C14_TesA_AcACP - c_C16_TesA_AcACP - c_C18_TesA_AcACP - c_C20_TesA_AcACP...
    - c_C12_TesA_AcACP_un - c_C14_TesA_AcACP_un - c_C16_TesA_AcACP_un - c_C18_TesA_AcACP_un - c_C20_TesA_AcACP_un;

% FabF
c_FabF = P.FabFtot - c_FabF_ACP - c_FabF_AcCoA - c_C2_FabF_Act - c_FabF_MalACP - c_C2_FabF_AcACP...
    - c_C4_FabF_AcACP - c_C6_FabF_AcACP - c_C8_FabF_AcACP - c_C10_FabF_AcACP - c_C12_FabF_AcACP - c_C14_FabF_AcACP - c_C16_FabF_AcACP - c_C18_FabF_AcACP...
    - c_C12_FabF_AcACP_un - c_C14_FabF_AcACP_un - c_C16_FabF_AcACP_un - c_C18_FabF_AcACP_un...
    - c_C4_FabF_Act - c_C6_FabF_Act - c_C8_FabF_Act - c_C10_FabF_Act - c_C12_FabF_Act - c_C14_FabF_Act - c_C16_FabF_Act - c_C18_FabF_Act...
    - c_C12_FabF_Act_un - c_C14_FabF_Act_un - c_C16_FabF_Act_un - c_C18_FabF_Act_un...
    - c_C2_FabF_Act_MalACP - c_C4_FabF_Act_MalACP - c_C6_FabF_Act_MalACP - c_C8_FabF_Act_MalACP - c_C10_FabF_Act_MalACP - c_C12_FabF_Act_MalACP - c_C14_FabF_Act_MalACP - c_C16_FabF_Act_MalACP - c_C18_FabF_Act_MalACP...
    - c_C12_FabF_Act_MalACP_un - c_C14_FabF_Act_MalACP_un - c_C16_FabF_Act_MalACP_un - c_C18_FabF_Act_MalACP_un;

% FabA
c_FabA = P.FabAtot - c_FabA_ACP - c_C10_FabA_cis3EnAcACP...
    - c_C4_FabA_BHyAcACP - c_C6_FabA_BHyAcACP - c_C8_FabA_BHyAcACP - c_C10_FabA_BHyAcACP - c_C12_FabA_BHyAcACP - c_C14_FabA_BHyAcACP - c_C16_FabA_BHyAcACP - c_C18_FabA_BHyAcACP - c_C20_FabA_BHyAcACP...
    - c_C12_FabA_BHyAcACP_un - c_C14_FabA_BHyAcACP_un - c_C16_FabA_BHyAcACP_un - c_C18_FabA_BHyAcACP_un - c_C20_FabA_BHyAcACP_un...
    - c_C4_FabA_EnAcACP - c_C6_FabA_EnAcACP - c_C8_FabA_EnAcACP - c_C10_FabA_EnAcACP - c_C12_FabA_EnAcACP - c_C14_FabA_EnAcACP - c_C16_FabA_EnAcACP - c_C18_FabA_EnAcACP - c_C20_FabA_EnAcACP...
    - c_C12_FabA_EnAcACP_un - c_C14_FabA_EnAcACP_un - c_C16_FabA_EnAcACP_un - c_C18_FabA_EnAcACP_un - c_C20_FabA_EnAcACP_un;

% FabB
c_FabB = P.FabBtot - c_FabB_ACP - c_FabB_AcCoA - c_C2_FabB_Act - c_C2_FabB_Act_MalACP - c_FabB_MalACP - c_C2_FabB_AcACP...
    - c_C4_FabB_AcACP - c_C6_FabB_AcACP - c_C8_FabB_AcACP - c_C10_FabB_AcACP - c_C12_FabB_AcACP - c_C14_FabB_AcACP - c_C16_FabB_AcACP - c_C18_FabB_AcACP...
    - c_C12_FabB_AcACP_un - c_C14_FabB_AcACP_un - c_C16_FabB_AcACP_un - c_C18_FabB_AcACP_un...
    - c_C4_FabB_Act - c_C6_FabB_Act - c_C8_FabB_Act - c_C10_FabB_Act - c_C12_FabB_Act - c_C14_FabB_Act - c_C16_FabB_Act - c_C18_FabB_Act...
    - c_C12_FabB_Act_un - c_C14_FabB_Act_un - c_C16_FabB_Act_un - c_C18_FabB_Act_un...
    - c_C4_FabB_Act_MalACP - c_C6_FabB_Act_MalACP - c_C8_FabB_Act_MalACP - c_C10_FabB_Act_MalACP - c_C12_FabB_Act_MalACP - c_C14_FabB_Act_MalACP - c_C16_FabB_Act_MalACP - c_C18_FabB_Act_MalACP...
    - c_C12_FabB_Act_MalACP_un - c_C14_FabB_Act_MalACP_un - c_C16_FabB_Act_MalACP_un - c_C18_FabB_Act_MalACP_un...
    - c_C10_FabB_cis3EnAcACP - c_C10_FabB_Act_cis3 - c_C10_FabB_Act_cis3MalACP;

CoA = c_CoA(end) - c_CoA(1)...
    + c_AcCoA(end) - c_AcCoA(1)...
    + c_SucCoA(end) - c_SucCoA(1)...
    + c_HexCoA(end) - c_HexCoA(1)...
    + c_OcCoA(end) - c_OcCoA(1)...
    + c_DecCoA(end) - c_DecCoA(1)...
    + c_LauCoA(end) - c_LauCoA(1)...
    + c_EthCoA(end) - c_EthCoA(1)...
    + c_PalCoA(end) - c_PalCoA(1)...
    + c_OcDecCoA(end) - c_OcDecCoA(1)...
    + c_MalCoA(end) - c_MalCoA(1)...
    + c_FabD_MalCoA(end) - c_FabD_MalCoA(1)...
    + c_C2_FabH_CoA(end) - c_C2_FabH_CoA(1)...
    + c_C4_FabH_CoA(end) - c_C4_FabH_CoA(1)...
    + c_C6_FabH_CoA(end) - c_C6_FabH_CoA(1)...
    + c_C8_FabH_CoA(end) - c_C8_FabH_CoA(1)...
    + c_C10_FabH_CoA(end) - c_C10_FabH_CoA(1)...
    + c_C12_FabH_CoA(end) - c_C12_FabH_CoA(1)...
    + c_C14_FabH_CoA(end) - c_C14_FabH_CoA(1)...
    + c_C16_FabH_CoA(end) - c_C16_FabH_CoA(1)...
    + c_C18_FabH_CoA(end) - c_C18_FabH_CoA(1)...
    + c_FabB_AcCoA(end) - c_FabB_AcCoA(1)...
    + c_FabF_AcCoA(end) - c_FabF_AcCoA(1);
    
ACP = c_ACP(end) - c_ACP(1)...
    + c_MalACP(end) - c_MalACP(1)...
    + c_C4_BKeACP(end) - c_C4_BKeACP(1)...
    + c_C6_BKeACP(end) - c_C6_BKeACP(1)...
    + c_C8_BKeACP(end) - c_C8_BKeACP(1)...
    + c_C10_BKeACP(end) - c_C10_BKeACP(1)...
    + c_C12_BKeACP(end) - c_C12_BKeACP(1)...
    + c_C14_BKeACP(end) - c_C14_BKeACP(1)...
    + c_C16_BKeACP(end) - c_C16_BKeACP(1)...
    + c_C18_BKeACP(end) - c_C18_BKeACP(1)...
    + c_C20_BKeACP(end) - c_C20_BKeACP(1)...
    + c_C12_BKeACP_un(end) - c_C12_BKeACP_un(1)...
    + c_C14_BKeACP_un(end) - c_C14_BKeACP_un(1)...
    + c_C16_BKeACP_un(end) - c_C16_BKeACP_un(1)...
    + c_C18_BKeACP_un(end) - c_C18_BKeACP_un(1)...
    + c_C20_BKeACP_un(end) - c_C20_BKeACP_un(1)...
    + c_C4_BHyAcACP(end) - c_C4_BHyAcACP(1)...
    + c_C6_BHyAcACP(end) - c_C6_BHyAcACP(1)...
    + c_C8_BHyAcACP(end) - c_C8_BHyAcACP(1)...
    + c_C10_BHyAcACP(end) - c_C10_BHyAcACP(1)...
    + c_C12_BHyAcACP(end) - c_C12_BHyAcACP(1)...
    + c_C14_BHyAcACP(end) - c_C14_BHyAcACP(1)...
    + c_C16_BHyAcACP(end) - c_C16_BHyAcACP(1)...
    + c_C18_BHyAcACP(end) - c_C18_BHyAcACP(1)...
    + c_C20_BHyAcACP(end) - c_C20_BHyAcACP(1)...
    + c_C12_BHyAcACP_un(end) - c_C12_BHyAcACP_un(1)...
    + c_C14_BHyAcACP_un(end) - c_C14_BHyAcACP_un(1)...
    + c_C16_BHyAcACP_un(end) - c_C16_BHyAcACP_un(1)...
    + c_C18_BHyAcACP_un(end) - c_C18_BHyAcACP_un(1)...
    + c_C20_BHyAcACP_un(end) - c_C20_BHyAcACP_un(1)...
    + c_C4_EnAcACP(end) - c_C4_EnAcACP(1)...
    + c_C6_EnAcACP(end) - c_C6_EnAcACP(1)...
    + c_C8_EnAcACP(end) - c_C8_EnAcACP(1)...
    + c_C10_EnAcACP(end) - c_C10_EnAcACP(1)...
    + c_C12_EnAcACP(end) - c_C12_EnAcACP(1)...
    + c_C14_EnAcACP(end) - c_C14_EnAcACP(1)...
    + c_C16_EnAcACP(end) - c_C16_EnAcACP(1)...
    + c_C18_EnAcACP(end) - c_C18_EnAcACP(1)...
    + c_C20_EnAcACP(end) - c_C20_EnAcACP(1)...
    + c_C10_cis3EnAcACP(end) - c_C10_cis3EnAcACP(1)...
    + c_C12_EnAcACP_un(end) - c_C12_EnAcACP_un(1)...
    + c_C14_EnAcACP_un(end) - c_C14_EnAcACP_un(1)...
    + c_C16_EnAcACP_un(end) - c_C16_EnAcACP_un(1)...
    + c_C18_EnAcACP_un(end) - c_C18_EnAcACP_un(1)...
    + c_C20_EnAcACP_un(end) - c_C20_EnAcACP_un(1)...
    + c_C4_AcACP(end) - c_C4_AcACP(1)...
    + c_C6_AcACP(end) - c_C6_AcACP(1)...
    + c_C8_AcACP(end) - c_C8_AcACP(1)...
    + c_C10_AcACP(end) - c_C10_AcACP(1)...
    + c_C12_AcACP(end) - c_C12_AcACP(1)...
    + c_C14_AcACP(end) - c_C14_AcACP(1)...
    + c_C16_AcACP(end) - c_C16_AcACP(1)...
    + c_C18_AcACP(end) - c_C18_AcACP(1)...
    + c_C20_AcACP(end) - c_C20_AcACP(1)...
    + c_C12_AcACP_un(end) - c_C12_AcACP_un(1)...
    + c_C14_AcACP_un(end) - c_C14_AcACP_un(1)...
    + c_C16_AcACP_un(end) - c_C16_AcACP_un(1)...
    + c_C18_AcACP_un(end) - c_C18_AcACP_un(1)...
    + c_C20_AcACP_un(end) - c_C20_AcACP_un(1)...
    + c_FabD_Act_ACP(end) - c_FabD_Act_ACP(1)...
    + c_C2_FabH_Act_MalACP(end) - c_C2_FabH_Act_MalACP(1)...
    + c_C4_FabH_Act_MalACP(end) - c_C4_FabH_Act_MalACP(1)...
    + c_C6_FabH_Act_MalACP(end) - c_C6_FabH_Act_MalACP(1)...
    + c_C8_FabH_Act_MalACP(end) - c_C8_FabH_Act_MalACP(1)...
    + c_C10_FabH_Act_MalACP(end) - c_C10_FabH_Act_MalACP(1)...
    + c_C12_FabH_Act_MalACP(end) - c_C12_FabH_Act_MalACP(1)...
    + c_C14_FabH_Act_MalACP(end) - c_C14_FabH_Act_MalACP(1)...
    + c_C16_FabH_Act_MalACP(end) - c_C16_FabH_Act_MalACP(1)...
    + c_C18_FabH_Act_MalACP(end) - c_C18_FabH_Act_MalACP(1)...
    + c_C4_FabG_NADPH_BKeACP(end) - c_C4_FabG_NADPH_BKeACP(1)...
    + c_C6_FabG_NADPH_BKeACP(end) - c_C6_FabG_NADPH_BKeACP(1)...
    + c_C8_FabG_NADPH_BKeACP(end) - c_C8_FabG_NADPH_BKeACP(1)...
    + c_C10_FabG_NADPH_BKeACP(end) - c_C10_FabG_NADPH_BKeACP(1)...
    + c_C12_FabG_NADPH_BKeACP(end) - c_C12_FabG_NADPH_BKeACP(1)...
    + c_C14_FabG_NADPH_BKeACP(end) - c_C14_FabG_NADPH_BKeACP(1)...
    + c_C16_FabG_NADPH_BKeACP(end) - c_C16_FabG_NADPH_BKeACP(1)...
    + c_C18_FabG_NADPH_BKeACP(end) - c_C18_FabG_NADPH_BKeACP(1)...
    + c_C20_FabG_NADPH_BKeACP(end) - c_C20_FabG_NADPH_BKeACP(1)...
    + c_C12_FabG_NADPH_BKeACP_un(end) - c_C12_FabG_NADPH_BKeACP_un(1)...
    + c_C14_FabG_NADPH_BKeACP_un(end) - c_C14_FabG_NADPH_BKeACP_un(1)...
    + c_C16_FabG_NADPH_BKeACP_un(end) - c_C16_FabG_NADPH_BKeACP_un(1)...
    + c_C18_FabG_NADPH_BKeACP_un(end) - c_C18_FabG_NADPH_BKeACP_un(1)...
    + c_C20_FabG_NADPH_BKeACP_un(end) - c_C20_FabG_NADPH_BKeACP_un(1)...
    + c_C4_FabZ_BHyAcACP(end) - c_C4_FabZ_BHyAcACP(1)...
    + c_C6_FabZ_BHyAcACP(end) - c_C6_FabZ_BHyAcACP(1)...
    + c_C8_FabZ_BHyAcACP(end) - c_C8_FabZ_BHyAcACP(1)...
    + c_C10_FabZ_BHyAcACP(end) - c_C10_FabZ_BHyAcACP(1)...
    + c_C12_FabZ_BHyAcACP(end) - c_C12_FabZ_BHyAcACP(1)...
    + c_C14_FabZ_BHyAcACP(end) - c_C14_FabZ_BHyAcACP(1)...
    + c_C16_FabZ_BHyAcACP(end) - c_C16_FabZ_BHyAcACP(1)...
    + c_C18_FabZ_BHyAcACP(end) - c_C18_FabZ_BHyAcACP(1)...
    + c_C20_FabZ_BHyAcACP(end) - c_C20_FabZ_BHyAcACP(1)...
    + c_C12_FabZ_BHyAcACP_un(end) - c_C12_FabZ_BHyAcACP_un(1)...
    + c_C14_FabZ_BHyAcACP_un(end) - c_C14_FabZ_BHyAcACP_un(1)...
    + c_C16_FabZ_BHyAcACP_un(end) - c_C16_FabZ_BHyAcACP_un(1)...
    + c_C18_FabZ_BHyAcACP_un(end) - c_C18_FabZ_BHyAcACP_un(1)...
    + c_C20_FabZ_BHyAcACP_un(end) - c_C20_FabZ_BHyAcACP_un(1)...
    + c_C4_FabZ_EnAcACP(end) - c_C4_FabZ_EnAcACP(1)...
    + c_C6_FabZ_EnAcACP(end) - c_C6_FabZ_EnAcACP(1)...
    + c_C8_FabZ_EnAcACP(end) - c_C8_FabZ_EnAcACP(1)...
    + c_C10_FabZ_EnAcACP(end) - c_C10_FabZ_EnAcACP(1)...
    + c_C12_FabZ_EnAcACP(end) - c_C12_FabZ_EnAcACP(1)...
    + c_C14_FabZ_EnAcACP(end) - c_C14_FabZ_EnAcACP(1)...
    + c_C16_FabZ_EnAcACP(end) - c_C16_FabZ_EnAcACP(1)...
    + c_C18_FabZ_EnAcACP(end) - c_C18_FabZ_EnAcACP(1)...
    + c_C20_FabZ_EnAcACP(end) - c_C20_FabZ_EnAcACP(1)...
    + c_C12_FabZ_EnAcACP_un(end) - c_C12_FabZ_EnAcACP_un(1)...
    + c_C14_FabZ_EnAcACP_un(end) - c_C14_FabZ_EnAcACP_un(1)...
    + c_C16_FabZ_EnAcACP_un(end) - c_C16_FabZ_EnAcACP_un(1)...
    + c_C18_FabZ_EnAcACP_un(end) - c_C18_FabZ_EnAcACP_un(1)...
    + c_C20_FabZ_EnAcACP_un(end) - c_C20_FabZ_EnAcACP_un(1)...
    + c_C4_FabA_BHyAcACP(end) - c_C4_FabA_BHyAcACP(1)...
    + c_C6_FabA_BHyAcACP(end) - c_C6_FabA_BHyAcACP(1)...
    + c_C8_FabA_BHyAcACP(end) - c_C8_FabA_BHyAcACP(1)...
    + c_C10_FabA_BHyAcACP(end) - c_C10_FabA_BHyAcACP(1)...
    + c_C12_FabA_BHyAcACP(end) - c_C12_FabA_BHyAcACP(1)...
    + c_C14_FabA_BHyAcACP(end) - c_C14_FabA_BHyAcACP(1)...
    + c_C16_FabA_BHyAcACP(end) - c_C16_FabA_BHyAcACP(1)...
    + c_C18_FabA_BHyAcACP(end) - c_C18_FabA_BHyAcACP(1)...
    + c_C20_FabA_BHyAcACP(end) - c_C20_FabA_BHyAcACP(1)...
    + c_C12_FabA_BHyAcACP_un(end) - c_C12_FabA_BHyAcACP_un(1)...
    + c_C14_FabA_BHyAcACP_un(end) - c_C14_FabA_BHyAcACP_un(1)...
    + c_C16_FabA_BHyAcACP_un(end) - c_C16_FabA_BHyAcACP_un(1)...
    + c_C18_FabA_BHyAcACP_un(end) - c_C18_FabA_BHyAcACP_un(1)...
    + c_C20_FabA_BHyAcACP_un(end) - c_C20_FabA_BHyAcACP_un(1)...
    + c_C4_FabA_EnAcACP(end) - c_C4_FabA_EnAcACP(1)...
    + c_C6_FabA_EnAcACP(end) - c_C6_FabA_EnAcACP(1)...
    + c_C8_FabA_EnAcACP(end) - c_C8_FabA_EnAcACP(1)...
    + c_C10_FabA_EnAcACP(end) - c_C10_FabA_EnAcACP(1)...
    + c_C12_FabA_EnAcACP(end) - c_C12_FabA_EnAcACP(1)...
    + c_C14_FabA_EnAcACP(end) - c_C14_FabA_EnAcACP(1)...
    + c_C16_FabA_EnAcACP(end) - c_C16_FabA_EnAcACP(1)...
    + c_C18_FabA_EnAcACP(end) - c_C18_FabA_EnAcACP(1)...
    + c_C20_FabA_EnAcACP(end) - c_C20_FabA_EnAcACP(1)...
    + c_C10_FabA_cis3EnAcACP(end) - c_C10_FabA_cis3EnAcACP(1)...
    + c_C12_FabA_EnAcACP_un(end) - c_C12_FabA_EnAcACP_un(1)...
    + c_C14_FabA_EnAcACP_un(end) - c_C14_FabA_EnAcACP_un(1)...
    + c_C16_FabA_EnAcACP_un(end) - c_C16_FabA_EnAcACP_un(1)...
    + c_C18_FabA_EnAcACP_un(end) - c_C18_FabA_EnAcACP_un(1)...
    + c_C20_FabA_EnAcACP_un(end) - c_C20_FabA_EnAcACP_un(1)...
    + c_C4_FabI_NADH_EnAcACP(end) - c_C4_FabI_NADH_EnAcACP(1)...
    + c_C6_FabI_NADH_EnAcACP(end) - c_C6_FabI_NADH_EnAcACP(1)...
    + c_C8_FabI_NADH_EnAcACP(end) - c_C8_FabI_NADH_EnAcACP(1)...
    + c_C10_FabI_NADH_EnAcACP(end) - c_C10_FabI_NADH_EnAcACP(1)...
    + c_C12_FabI_NADH_EnAcACP(end) - c_C12_FabI_NADH_EnAcACP(1)...
    + c_C14_FabI_NADH_EnAcACP(end) - c_C14_FabI_NADH_EnAcACP(1)...
    + c_C16_FabI_NADH_EnAcACP(end) - c_C16_FabI_NADH_EnAcACP(1)...
    + c_C18_FabI_NADH_EnAcACP(end) - c_C18_FabI_NADH_EnAcACP(1)...
    + c_C20_FabI_NADH_EnAcACP(end) - c_C20_FabI_NADH_EnAcACP(1)...
    + c_C12_FabI_NADH_EnAcACP_un(end) - c_C12_FabI_NADH_EnAcACP_un(1)...
    + c_C14_FabI_NADH_EnAcACP_un(end) - c_C14_FabI_NADH_EnAcACP_un(1)...
    + c_C16_FabI_NADH_EnAcACP_un(end) - c_C16_FabI_NADH_EnAcACP_un(1)...
    + c_C18_FabI_NADH_EnAcACP_un(end) - c_C18_FabI_NADH_EnAcACP_un(1)...
    + c_C20_FabI_NADH_EnAcACP_un(end) - c_C20_FabI_NADH_EnAcACP_un(1)...
    + c_C4_TesA_AcACP(end) - c_C4_TesA_AcACP(1)...
    + c_C6_TesA_AcACP(end) - c_C6_TesA_AcACP(1)...
    + c_C8_TesA_AcACP(end) - c_C8_TesA_AcACP(1)...
    + c_C10_TesA_AcACP(end) - c_C10_TesA_AcACP(1)...
    + c_C12_TesA_AcACP(end) - c_C12_TesA_AcACP(1)...
    + c_C14_TesA_AcACP(end) - c_C14_TesA_AcACP(1)...
    + c_C16_TesA_AcACP(end) - c_C16_TesA_AcACP(1)...
    + c_C18_TesA_AcACP(end) - c_C18_TesA_AcACP(1)...
    + c_C20_TesA_AcACP(end) - c_C20_TesA_AcACP(1)...
    + c_C12_TesA_AcACP_un(end) - c_C12_TesA_AcACP_un(1)...
    + c_C14_TesA_AcACP_un(end) - c_C14_TesA_AcACP_un(1)...
    + c_C16_TesA_AcACP_un(end) - c_C16_TesA_AcACP_un(1)...
    + c_C18_TesA_AcACP_un(end) - c_C18_TesA_AcACP_un(1)...
    + c_C20_TesA_AcACP_un(end) - c_C20_TesA_AcACP_un(1)...
    + c_C4_FabF_AcACP(end) - c_C4_FabF_AcACP(1)...
    + c_C6_FabF_AcACP(end) - c_C6_FabF_AcACP(1)...
    + c_C8_FabF_AcACP(end) - c_C8_FabF_AcACP(1)...
    + c_C10_FabF_AcACP(end) - c_C10_FabF_AcACP(1)...
    + c_C12_FabF_AcACP(end) - c_C12_FabF_AcACP(1)...
    + c_C14_FabF_AcACP(end) - c_C14_FabF_AcACP(1)...
    + c_C16_FabF_AcACP(end) - c_C16_FabF_AcACP(1)...
    + c_C18_FabF_AcACP(end) - c_C18_FabF_AcACP(1)...
    + c_C12_FabF_AcACP_un(end) - c_C12_FabF_AcACP_un(1)...
    + c_C14_FabF_AcACP_un(end) - c_C14_FabF_AcACP_un(1)...
    + c_C16_FabF_AcACP_un(end) - c_C16_FabF_AcACP_un(1)...
    + c_C18_FabF_AcACP_un(end) - c_C18_FabF_AcACP_un(1)...
    + c_C4_FabF_Act_MalACP(end) - c_C4_FabF_Act_MalACP(1)...
    + c_C6_FabF_Act_MalACP(end) - c_C6_FabF_Act_MalACP(1)...
    + c_C8_FabF_Act_MalACP(end) - c_C8_FabF_Act_MalACP(1)...
    + c_C10_FabF_Act_MalACP(end) - c_C10_FabF_Act_MalACP(1)...
    + c_C12_FabF_Act_MalACP(end) - c_C12_FabF_Act_MalACP(1)...
    + c_C14_FabF_Act_MalACP(end) - c_C14_FabF_Act_MalACP(1)...
    + c_C16_FabF_Act_MalACP(end) - c_C16_FabF_Act_MalACP(1)...
    + c_C18_FabF_Act_MalACP(end) - c_C18_FabF_Act_MalACP(1)...
    + c_C12_FabF_Act_MalACP_un(end) - c_C12_FabF_Act_MalACP_un(1)...
    + c_C14_FabF_Act_MalACP_un(end) - c_C14_FabF_Act_MalACP_un(1)...
    + c_C16_FabF_Act_MalACP_un(end) - c_C16_FabF_Act_MalACP_un(1)...
    + c_C18_FabF_Act_MalACP_un(end) - c_C18_FabF_Act_MalACP_un(1)...
    + c_C4_FabB_AcACP(end) - c_C4_FabB_AcACP(1)...
    + c_C6_FabB_AcACP(end) - c_C6_FabB_AcACP(1)...
    + c_C8_FabB_AcACP(end) - c_C8_FabB_AcACP(1)...
    + c_C10_FabB_AcACP(end) - c_C10_FabB_AcACP(1)...
    + c_C12_FabB_AcACP(end) - c_C12_FabB_AcACP(1)...
    + c_C14_FabB_AcACP(end) - c_C14_FabB_AcACP(1)...
    + c_C16_FabB_AcACP(end) - c_C16_FabB_AcACP(1)...
    + c_C18_FabB_AcACP(end) - c_C18_FabB_AcACP(1)...
    + c_C12_FabB_AcACP_un(end) - c_C12_FabB_AcACP_un(1)...
    + c_C14_FabB_AcACP_un(end) - c_C14_FabB_AcACP_un(1)...
    + c_C16_FabB_AcACP_un(end) - c_C16_FabB_AcACP_un(1)...
    + c_C18_FabB_AcACP_un(end) - c_C18_FabB_AcACP_un(1)...
    + c_C4_FabB_Act_MalACP(end) - c_C4_FabB_Act_MalACP(1)...
    + c_C6_FabB_Act_MalACP(end) - c_C6_FabB_Act_MalACP(1)...
    + c_C8_FabB_Act_MalACP(end) - c_C8_FabB_Act_MalACP(1)...
    + c_C10_FabB_Act_MalACP(end) - c_C10_FabB_Act_MalACP(1)...
    + c_C12_FabB_Act_MalACP(end) - c_C12_FabB_Act_MalACP(1)...
    + c_C14_FabB_Act_MalACP(end) - c_C14_FabB_Act_MalACP(1)...
    + c_C16_FabB_Act_MalACP(end) - c_C16_FabB_Act_MalACP(1)...
    + c_C18_FabB_Act_MalACP(end) - c_C18_FabB_Act_MalACP(1)...
    + c_C12_FabB_Act_MalACP_un(end) - c_C12_FabB_Act_MalACP_un(1)...
    + c_C14_FabB_Act_MalACP_un(end) - c_C14_FabB_Act_MalACP_un(1)...
    + c_C16_FabB_Act_MalACP_un(end) - c_C16_FabB_Act_MalACP_un(1)...
    + c_C18_FabB_Act_MalACP_un(end) - c_C18_FabB_Act_MalACP_un(1)...
    + c_C10_FabB_cis3EnAcACP(end) - c_C10_FabB_cis3EnAcACP(1)...
    + c_C10_FabB_Act_cis3MalACP(end) - c_C10_FabB_Act_cis3MalACP(1)...
    + c_C4_FabH_AcACP(end) - c_C4_FabH_AcACP(1)...
    + c_C6_FabH_AcACP(end) - c_C6_FabH_AcACP(1)...
    + c_C8_FabH_AcACP(end) - c_C8_FabH_AcACP(1)...
    + c_C10_FabH_AcACP(end) - c_C10_FabH_AcACP(1)...
    + c_C12_FabH_AcACP(end) - c_C12_FabH_AcACP(1)...
    + c_C14_FabH_AcACP(end) - c_C14_FabH_AcACP(1)...
    + c_C16_FabH_AcACP(end) - c_C16_FabH_AcACP(1)...
    + c_C18_FabH_AcACP(end) - c_C18_FabH_AcACP(1)...
    + c_C20_FabH_AcACP(end) - c_C20_FabH_AcACP(1)...
    + c_C12_FabH_AcACP_un(end) - c_C12_FabH_AcACP_un(1)...
    + c_C14_FabH_AcACP_un(end) - c_C14_FabH_AcACP_un(1)...
    + c_C16_FabH_AcACP_un(end) - c_C16_FabH_AcACP_un(1)...
    + c_C18_FabH_AcACP_un(end) - c_C18_FabH_AcACP_un(1)...
    + c_C20_FabH_AcACP_un(end) - c_C20_FabH_AcACP_un(1)...
    + c_C4_FabH_Act_AcACP(end) - c_C4_FabH_Act_AcACP(1)...
    + c_C6_FabH_Act_AcACP(end) - c_C6_FabH_Act_AcACP(1)...
    + c_C8_FabH_Act_AcACP(end) - c_C8_FabH_Act_AcACP(1)...
    + c_C10_FabH_Act_AcACP(end) - c_C10_FabH_Act_AcACP(1)...
    + c_C12_FabH_Act_AcACP(end) - c_C12_FabH_Act_AcACP(1)...
    + c_C14_FabH_Act_AcACP(end) - c_C14_FabH_Act_AcACP(1)...
    + c_C16_FabH_Act_AcACP(end) - c_C16_FabH_Act_AcACP(1)...
    + c_C18_FabH_Act_AcACP(end) - c_C18_FabH_Act_AcACP(1)...
    + c_C20_FabH_Act_AcACP(end) - c_C20_FabH_Act_AcACP(1)...
    + c_C12_FabH_Act_AcACP_un(end) - c_C12_FabH_Act_AcACP_un(1)...
    + c_C14_FabH_Act_AcACP_un(end) - c_C14_FabH_Act_AcACP_un(1)...
    + c_C16_FabH_Act_AcACP_un(end) - c_C16_FabH_Act_AcACP_un(1)...
    + c_C18_FabH_Act_AcACP_un(end) - c_C18_FabH_Act_AcACP_un(1)...
    + c_C20_FabH_Act_AcACP_un(end) - c_C20_FabH_Act_AcACP_un(1)...
    + c_TesA_ACP(end) - c_TesA_ACP(1)...
    + c_FabH_ACP(end) - c_FabH_ACP(1)...
    + c_FabG_ACP(end) - c_FabG_ACP(1)...
    + c_FabZ_ACP(end) - c_FabZ_ACP(1)...
    + c_FabI_ACP(end) - c_FabI_ACP(1)...
    + c_FabF_ACP(end) - c_FabF_ACP(1)...
    + c_FabA_ACP(end) - c_FabA_ACP(1)...
    + c_FabB_ACP(end) - c_FabB_ACP(1)...
    + c_C2_FabB_Act_MalACP(end) - c_C2_FabB_Act_MalACP(1)...
    + c_C2_FabF_Act_MalACP(end) - c_C2_FabF_Act_MalACP(1)...
    + c_FabB_MalACP(end) - c_FabB_MalACP(1)...
    + c_AcACP(end) - c_AcACP(1)...
    + c_C2_FabB_AcACP(end) - c_C2_FabB_AcACP(1)...
    + c_FabF_MalACP(end) - c_FabF_MalACP(1)...
    + c_C2_FabF_AcACP(end) - c_C2_FabF_AcACP(1);
    
NADH = c_NADH(end) - c_NADH(1)...
    + c_FabI_NADH(end) - c_FabI_NADH(1)...
    + c_C4_FabI_NADH_EnAcACP(end) - c_C4_FabI_NADH_EnAcACP(1)...
    + c_C6_FabI_NADH_EnAcACP(end) - c_C6_FabI_NADH_EnAcACP(1)...
    + c_C8_FabI_NADH_EnAcACP(end) - c_C8_FabI_NADH_EnAcACP(1)...
    + c_C10_FabI_NADH_EnAcACP(end) - c_C10_FabI_NADH_EnAcACP(1)...
    + c_C12_FabI_NADH_EnAcACP(end) - c_C12_FabI_NADH_EnAcACP(1)...
    + c_C14_FabI_NADH_EnAcACP(end) - c_C14_FabI_NADH_EnAcACP(1)...
    + c_C16_FabI_NADH_EnAcACP(end) - c_C16_FabI_NADH_EnAcACP(1)...
    + c_C18_FabI_NADH_EnAcACP(end) - c_C18_FabI_NADH_EnAcACP(1)...
    + c_C20_FabI_NADH_EnAcACP(end) - c_C20_FabI_NADH_EnAcACP(1)...
    + c_C12_FabI_NADH_EnAcACP_un(end) - c_C12_FabI_NADH_EnAcACP_un(1)...
    + c_C14_FabI_NADH_EnAcACP_un(end) - c_C14_FabI_NADH_EnAcACP_un(1)...
    + c_C16_FabI_NADH_EnAcACP_un(end) - c_C16_FabI_NADH_EnAcACP_un(1)...
    + c_C18_FabI_NADH_EnAcACP_un(end) - c_C18_FabI_NADH_EnAcACP_un(1)...
    + c_C20_FabI_NADH_EnAcACP_un(end) - c_C20_FabI_NADH_EnAcACP_un(1)...
    + c_NAD(end) - c_NAD(1);
    
NADPH = c_NADPH(end) - c_NADPH(1)...
    + c_FabG_NADPH(end) - c_FabG_NADPH(1)...
    + c_C4_FabG_NADPH_BKeACP(end) - c_C4_FabG_NADPH_BKeACP(1)...
    + c_C6_FabG_NADPH_BKeACP(end) - c_C6_FabG_NADPH_BKeACP(1)...
    + c_C8_FabG_NADPH_BKeACP(end) - c_C8_FabG_NADPH_BKeACP(1)...
    + c_C10_FabG_NADPH_BKeACP(end) - c_C10_FabG_NADPH_BKeACP(1)...
    + c_C12_FabG_NADPH_BKeACP(end) - c_C12_FabG_NADPH_BKeACP(1)...
    + c_C14_FabG_NADPH_BKeACP(end) - c_C14_FabG_NADPH_BKeACP(1)...
    + c_C16_FabG_NADPH_BKeACP(end) - c_C16_FabG_NADPH_BKeACP(1)...
    + c_C18_FabG_NADPH_BKeACP(end) - c_C18_FabG_NADPH_BKeACP(1)...
    + c_C20_FabG_NADPH_BKeACP(end) - c_C20_FabG_NADPH_BKeACP(1)...
    + c_C12_FabG_NADPH_BKeACP_un(end) - c_C12_FabG_NADPH_BKeACP_un(1)...
    + c_C14_FabG_NADPH_BKeACP_un(end) - c_C14_FabG_NADPH_BKeACP_un(1)...
    + c_C16_FabG_NADPH_BKeACP_un(end) - c_C16_FabG_NADPH_BKeACP_un(1)...
    + c_C18_FabG_NADPH_BKeACP_un(end) - c_C18_FabG_NADPH_BKeACP_un(1)...
    + c_C20_FabG_NADPH_BKeACP_un(end) - c_C20_FabG_NADPH_BKeACP_un(1)...
    + c_NADP(end) - c_NADP(1);
    
ATP = c_ATP(end) - c_ATP(1)...
    + c_ADP(end) - c_ADP(1)...
    + c_ACC_s1(end) - c_ACC_s1(1)...
    + c_ACC_s2(end) - c_ACC_s2(1)...
    + c_ACC_s3(end) - c_ACC_s3(1)...
    + c_ACC_s4(end) - c_ACC_s4(1);
    
ACC = c_ACC(end) - c_ACC(1)...
    + c_ACC_s1(end) - c_ACC_s1(1)...
    + c_ACC_s2(end) - c_ACC_s2(1)...
    + c_ACC_s3(end) - c_ACC_s3(1)...
    + c_ACC_s4(end) - c_ACC_s4(1);
    
FabD = c_FabD(end) - c_FabD(1)...
    + c_FabD_MalCoA(end) - c_FabD_MalCoA(1)...
    + c_FabD_Act(end) - c_FabD_Act(1)...
    + c_FabD_Act_ACP(end) - c_FabD_Act_ACP(1);

FabH = c_FabH(end) - c_FabH(1)...
    + c_C2_FabH_CoA(end) - c_C2_FabH_CoA(1)...
    + c_C4_FabH_CoA(end) - c_C4_FabH_CoA(1)...
    + c_C6_FabH_CoA(end) - c_C6_FabH_CoA(1)...
    + c_C8_FabH_CoA(end) - c_C8_FabH_CoA(1)...
    + c_C10_FabH_CoA(end) - c_C10_FabH_CoA(1)...
    + c_C12_FabH_CoA(end) - c_C12_FabH_CoA(1)...
    + c_C14_FabH_CoA(end) - c_C14_FabH_CoA(1)...
    + c_C16_FabH_CoA(end) - c_C16_FabH_CoA(1)...
    + c_C18_FabH_CoA(end) - c_C18_FabH_CoA(1)...
    + c_C2_FabH_Act(end) - c_C2_FabH_Act(1)...
    + c_C4_FabH_Act(end) - c_C4_FabH_Act(1)...
    + c_C6_FabH_Act(end) - c_C6_FabH_Act(1)...
    + c_C8_FabH_Act(end) - c_C8_FabH_Act(1)...
    + c_C10_FabH_Act(end) - c_C10_FabH_Act(1)...
    + c_C12_FabH_Act(end) - c_C12_FabH_Act(1)...
    + c_C14_FabH_Act(end) - c_C14_FabH_Act(1)...
    + c_C16_FabH_Act(end) - c_C16_FabH_Act(1)...
    + c_C18_FabH_Act(end) - c_C18_FabH_Act(1)...
    + c_C2_FabH_Act_MalACP(end) - c_C2_FabH_Act_MalACP(1)...
    + c_C4_FabH_Act_MalACP(end) - c_C4_FabH_Act_MalACP(1)...
    + c_C6_FabH_Act_MalACP(end) - c_C6_FabH_Act_MalACP(1)...
    + c_C8_FabH_Act_MalACP(end) - c_C8_FabH_Act_MalACP(1)...
    + c_C10_FabH_Act_MalACP(end) - c_C10_FabH_Act_MalACP(1)...
    + c_C12_FabH_Act_MalACP(end) - c_C12_FabH_Act_MalACP(1)...
    + c_C14_FabH_Act_MalACP(end) - c_C14_FabH_Act_MalACP(1)...
    + c_C16_FabH_Act_MalACP(end) - c_C16_FabH_Act_MalACP(1)...
    + c_C18_FabH_Act_MalACP(end) - c_C18_FabH_Act_MalACP(1)...
    + c_C4_FabH_AcACP(end) - c_C4_FabH_AcACP(1)...
    + c_C6_FabH_AcACP(end) - c_C6_FabH_AcACP(1)...
    + c_C8_FabH_AcACP(end) - c_C8_FabH_AcACP(1)...
    + c_C10_FabH_AcACP(end) - c_C10_FabH_AcACP(1)...
    + c_C12_FabH_AcACP(end) - c_C12_FabH_AcACP(1)...
    + c_C14_FabH_AcACP(end) - c_C14_FabH_AcACP(1)...
    + c_C16_FabH_AcACP(end) - c_C16_FabH_AcACP(1)...
    + c_C18_FabH_AcACP(end) - c_C18_FabH_AcACP(1)...
    + c_C20_FabH_AcACP(end) - c_C20_FabH_AcACP(1)...
    + c_C12_FabH_AcACP_un(end) - c_C12_FabH_AcACP_un(1)...
    + c_C14_FabH_AcACP_un(end) - c_C14_FabH_AcACP_un(1)...
    + c_C16_FabH_AcACP_un(end) - c_C16_FabH_AcACP_un(1)...
    + c_C18_FabH_AcACP_un(end) - c_C18_FabH_AcACP_un(1)...
    + c_C20_FabH_AcACP_un(end) - c_C20_FabH_AcACP_un(1)...
    + c_C4_FabH_Act_AcACP(end) - c_C4_FabH_Act_AcACP(1)...
    + c_C6_FabH_Act_AcACP(end) - c_C6_FabH_Act_AcACP(1)...
    + c_C8_FabH_Act_AcACP(end) - c_C8_FabH_Act_AcACP(1)...
    + c_C10_FabH_Act_AcACP(end) - c_C10_FabH_Act_AcACP(1)...
    + c_C12_FabH_Act_AcACP(end) - c_C12_FabH_Act_AcACP(1)...
    + c_C14_FabH_Act_AcACP(end) - c_C14_FabH_Act_AcACP(1)...
    + c_C16_FabH_Act_AcACP(end) - c_C16_FabH_Act_AcACP(1)...
    + c_C18_FabH_Act_AcACP(end) - c_C18_FabH_Act_AcACP(1)...
    + c_C20_FabH_Act_AcACP(end) - c_C20_FabH_Act_AcACP(1)...
    + c_C12_FabH_Act_AcACP_un(end) - c_C12_FabH_Act_AcACP_un(1)...
    + c_C14_FabH_Act_AcACP_un(end) - c_C14_FabH_Act_AcACP_un(1)...
    + c_C16_FabH_Act_AcACP_un(end) - c_C16_FabH_Act_AcACP_un(1)...
    + c_C18_FabH_Act_AcACP_un(end) - c_C18_FabH_Act_AcACP_un(1)...
    + c_C20_FabH_Act_AcACP_un(end) - c_C20_FabH_Act_AcACP_un(1)...
    + c_FabH_ACP(end) - c_FabH_ACP(1);

FabG = c_FabG(end) - c_FabG(1)...
    + c_FabG_NADPH(end) - c_FabG_NADPH(1)...
    + c_C4_FabG_NADPH_BKeACP(end) - c_C4_FabG_NADPH_BKeACP(1)...
    + c_C6_FabG_NADPH_BKeACP(end) - c_C6_FabG_NADPH_BKeACP(1)...
    + c_C8_FabG_NADPH_BKeACP(end) - c_C8_FabG_NADPH_BKeACP(1)...
    + c_C10_FabG_NADPH_BKeACP(end) - c_C10_FabG_NADPH_BKeACP(1)...
    + c_C12_FabG_NADPH_BKeACP(end) - c_C12_FabG_NADPH_BKeACP(1)...
    + c_C14_FabG_NADPH_BKeACP(end) - c_C14_FabG_NADPH_BKeACP(1)...
    + c_C16_FabG_NADPH_BKeACP(end) - c_C16_FabG_NADPH_BKeACP(1)...
    + c_C18_FabG_NADPH_BKeACP(end) - c_C18_FabG_NADPH_BKeACP(1)...
    + c_C20_FabG_NADPH_BKeACP(end) - c_C20_FabG_NADPH_BKeACP(1)...
    + c_C12_FabG_NADPH_BKeACP_un(end) - c_C12_FabG_NADPH_BKeACP_un(1)...
    + c_C14_FabG_NADPH_BKeACP_un(end) - c_C14_FabG_NADPH_BKeACP_un(1)...
    + c_C16_FabG_NADPH_BKeACP_un(end) - c_C16_FabG_NADPH_BKeACP_un(1)...
    + c_C18_FabG_NADPH_BKeACP_un(end) - c_C18_FabG_NADPH_BKeACP_un(1)...
    + c_C20_FabG_NADPH_BKeACP_un(end) - c_C20_FabG_NADPH_BKeACP_un(1)...
    + c_FabG_ACP(end) - c_FabG_ACP(1);

FabZ = c_FabZ(end) - c_FabZ(1)...
    + c_C4_FabZ_BHyAcACP(end) - c_C4_FabZ_BHyAcACP(1)...
    + c_C6_FabZ_BHyAcACP(end) - c_C6_FabZ_BHyAcACP(1)...
    + c_C8_FabZ_BHyAcACP(end) - c_C8_FabZ_BHyAcACP(1)...
    + c_C10_FabZ_BHyAcACP(end) - c_C10_FabZ_BHyAcACP(1)...
    + c_C12_FabZ_BHyAcACP(end) - c_C12_FabZ_BHyAcACP(1)...
    + c_C14_FabZ_BHyAcACP(end) - c_C14_FabZ_BHyAcACP(1)...
    + c_C16_FabZ_BHyAcACP(end) - c_C16_FabZ_BHyAcACP(1)...
    + c_C18_FabZ_BHyAcACP(end) - c_C18_FabZ_BHyAcACP(1)...
    + c_C20_FabZ_BHyAcACP(end) - c_C20_FabZ_BHyAcACP(1)...
    + c_C12_FabZ_BHyAcACP_un(end) - c_C12_FabZ_BHyAcACP_un(1)...
    + c_C14_FabZ_BHyAcACP_un(end) - c_C14_FabZ_BHyAcACP_un(1)...
    + c_C16_FabZ_BHyAcACP_un(end) - c_C16_FabZ_BHyAcACP_un(1)...
    + c_C18_FabZ_BHyAcACP_un(end) - c_C18_FabZ_BHyAcACP_un(1)...
    + c_C20_FabZ_BHyAcACP_un(end) - c_C20_FabZ_BHyAcACP_un(1)...
    + c_C4_FabZ_EnAcACP(end) - c_C4_FabZ_EnAcACP(1)...
    + c_C6_FabZ_EnAcACP(end) - c_C6_FabZ_EnAcACP(1)...
    + c_C8_FabZ_EnAcACP(end) - c_C8_FabZ_EnAcACP(1)...
    + c_C10_FabZ_EnAcACP(end) - c_C10_FabZ_EnAcACP(1)...
    + c_C12_FabZ_EnAcACP(end) - c_C12_FabZ_EnAcACP(1)...
    + c_C14_FabZ_EnAcACP(end) - c_C14_FabZ_EnAcACP(1)...
    + c_C16_FabZ_EnAcACP(end) - c_C16_FabZ_EnAcACP(1)...
    + c_C18_FabZ_EnAcACP(end) - c_C18_FabZ_EnAcACP(1)...
    + c_C20_FabZ_EnAcACP(end) - c_C20_FabZ_EnAcACP(1)...
    + c_C12_FabZ_EnAcACP_un(end) - c_C12_FabZ_EnAcACP_un(1)...
    + c_C14_FabZ_EnAcACP_un(end) - c_C14_FabZ_EnAcACP_un(1)...
    + c_C16_FabZ_EnAcACP_un(end) - c_C16_FabZ_EnAcACP_un(1)...
    + c_C18_FabZ_EnAcACP_un(end) - c_C18_FabZ_EnAcACP_un(1)...
    + c_C20_FabZ_EnAcACP_un(end) - c_C20_FabZ_EnAcACP_un(1)...
    + c_FabZ_ACP(end) - c_FabZ_ACP(1);

FabI = c_FabI(end) - c_FabI(1)...
    + c_FabI_NADH(end) - c_FabI_NADH(1)...
    + c_C4_FabI_NADH_EnAcACP(end) - c_C4_FabI_NADH_EnAcACP(1)...
    + c_C6_FabI_NADH_EnAcACP(end) - c_C6_FabI_NADH_EnAcACP(1)...
    + c_C8_FabI_NADH_EnAcACP(end) - c_C8_FabI_NADH_EnAcACP(1)...
    + c_C10_FabI_NADH_EnAcACP(end) - c_C10_FabI_NADH_EnAcACP(1)...
    + c_C12_FabI_NADH_EnAcACP(end) - c_C12_FabI_NADH_EnAcACP(1)...
    + c_C14_FabI_NADH_EnAcACP(end) - c_C14_FabI_NADH_EnAcACP(1)...
    + c_C16_FabI_NADH_EnAcACP(end) - c_C16_FabI_NADH_EnAcACP(1)...
    + c_C18_FabI_NADH_EnAcACP(end) - c_C18_FabI_NADH_EnAcACP(1)...
    + c_C20_FabI_NADH_EnAcACP(end) - c_C20_FabI_NADH_EnAcACP(1)...
    + c_C12_FabI_NADH_EnAcACP_un(end) - c_C12_FabI_NADH_EnAcACP_un(1)...
    + c_C14_FabI_NADH_EnAcACP_un(end) - c_C14_FabI_NADH_EnAcACP_un(1)...
    + c_C16_FabI_NADH_EnAcACP_un(end) - c_C16_FabI_NADH_EnAcACP_un(1)...
    + c_C18_FabI_NADH_EnAcACP_un(end) - c_C18_FabI_NADH_EnAcACP_un(1)...
    + c_C20_FabI_NADH_EnAcACP_un(end) - c_C20_FabI_NADH_EnAcACP_un(1)...
    + c_FabI_ACP(end) - c_FabI_ACP(1);

TesA = c_TesA(end) - c_TesA(1)...
    + c_C4_TesA_AcACP(end) - c_C4_TesA_AcACP(1)...
    + c_C6_TesA_AcACP(end) - c_C6_TesA_AcACP(1)...
    + c_C8_TesA_AcACP(end) - c_C8_TesA_AcACP(1)...
    + c_C10_TesA_AcACP(end) - c_C10_TesA_AcACP(1)...
    + c_C12_TesA_AcACP(end) - c_C12_TesA_AcACP(1)...
    + c_C14_TesA_AcACP(end) - c_C14_TesA_AcACP(1)...
    + c_C16_TesA_AcACP(end) - c_C16_TesA_AcACP(1)...
    + c_C18_TesA_AcACP(end) - c_C18_TesA_AcACP(1)...
    + c_C20_TesA_AcACP(end) - c_C20_TesA_AcACP(1)...
    + c_C12_TesA_AcACP_un(end) - c_C12_TesA_AcACP_un(1)...
    + c_C14_TesA_AcACP_un(end) - c_C14_TesA_AcACP_un(1)...
    + c_C16_TesA_AcACP_un(end) - c_C16_TesA_AcACP_un(1)...
    + c_C18_TesA_AcACP_un(end) - c_C18_TesA_AcACP_un(1)...
    + c_C20_TesA_AcACP_un(end) - c_C20_TesA_AcACP_un(1)...
    + c_TesA_ACP(end) - c_TesA_ACP(1);

FabF = c_FabF(end) - c_FabF(1)...
    + c_C4_FabF_AcACP(end) - c_C4_FabF_AcACP(1)...
    + c_C6_FabF_AcACP(end) - c_C6_FabF_AcACP(1)...
    + c_C8_FabF_AcACP(end) - c_C8_FabF_AcACP(1)...
    + c_C10_FabF_AcACP(end) - c_C10_FabF_AcACP(1)...
    + c_C12_FabF_AcACP(end) - c_C12_FabF_AcACP(1)...
    + c_C14_FabF_AcACP(end) - c_C14_FabF_AcACP(1)...
    + c_C16_FabF_AcACP(end) - c_C16_FabF_AcACP(1)...
    + c_C18_FabF_AcACP(end) - c_C18_FabF_AcACP(1)...
    + c_C12_FabF_AcACP_un(end) - c_C12_FabF_AcACP_un(1)...
    + c_C14_FabF_AcACP_un(end) - c_C14_FabF_AcACP_un(1)...
    + c_C16_FabF_AcACP_un(end) - c_C16_FabF_AcACP_un(1)...
    + c_C18_FabF_AcACP_un(end) - c_C18_FabF_AcACP_un(1)...
    + c_C4_FabF_Act(end) - c_C4_FabF_Act(1)...
    + c_C6_FabF_Act(end) - c_C6_FabF_Act(1)...
    + c_C8_FabF_Act(end) - c_C8_FabF_Act(1)...
    + c_C10_FabF_Act(end) - c_C10_FabF_Act(1)...
    + c_C12_FabF_Act(end) - c_C12_FabF_Act(1)...
    + c_C14_FabF_Act(end) - c_C14_FabF_Act(1)...
    + c_C16_FabF_Act(end) - c_C16_FabF_Act(1)...
    + c_C18_FabF_Act(end) - c_C18_FabF_Act(1)...
    + c_C12_FabF_Act_un(end) - c_C12_FabF_Act_un(1)...
    + c_C14_FabF_Act_un(end) - c_C14_FabF_Act_un(1)...
    + c_C16_FabF_Act_un(end) - c_C16_FabF_Act_un(1)...
    + c_C18_FabF_Act_un(end) - c_C18_FabF_Act_un(1)...
    + c_C4_FabF_Act_MalACP(end) - c_C4_FabF_Act_MalACP(1)...
    + c_C6_FabF_Act_MalACP(end) - c_C6_FabF_Act_MalACP(1)...
    + c_C8_FabF_Act_MalACP(end) - c_C8_FabF_Act_MalACP(1)...
    + c_C10_FabF_Act_MalACP(end) - c_C10_FabF_Act_MalACP(1)...
    + c_C12_FabF_Act_MalACP(end) - c_C12_FabF_Act_MalACP(1)...
    + c_C14_FabF_Act_MalACP(end) - c_C14_FabF_Act_MalACP(1)...
    + c_C16_FabF_Act_MalACP(end) - c_C16_FabF_Act_MalACP(1)...
    + c_C18_FabF_Act_MalACP(end) - c_C18_FabF_Act_MalACP(1)...
    + c_C12_FabF_Act_MalACP_un(end) - c_C12_FabF_Act_MalACP_un(1)...
    + c_C14_FabF_Act_MalACP_un(end) - c_C14_FabF_Act_MalACP_un(1)...
    + c_C16_FabF_Act_MalACP_un(end) - c_C16_FabF_Act_MalACP_un(1)...
    + c_C18_FabF_Act_MalACP_un(end) - c_C18_FabF_Act_MalACP_un(1)...
    + c_FabF_ACP(end) - c_FabF_ACP(1)...
    + c_FabF_AcCoA(end) - c_FabF_AcCoA(1)...
    + c_C2_FabF_Act(end) - c_C2_FabF_Act(1)...
    + c_C2_FabF_Act_MalACP(end) - c_C2_FabF_Act_MalACP(1)...
    + c_FabF_MalACP(end) - c_FabF_MalACP(1)...
    + c_C2_FabF_AcACP(end) - c_C2_FabF_AcACP(1);

FabA = c_FabA(end) - c_FabA(1)...
    + c_C4_FabA_BHyAcACP(end) - c_C4_FabA_BHyAcACP(1)...
    + c_C6_FabA_BHyAcACP(end) - c_C6_FabA_BHyAcACP(1)...
    + c_C8_FabA_BHyAcACP(end) - c_C8_FabA_BHyAcACP(1)...
    + c_C10_FabA_BHyAcACP(end) - c_C10_FabA_BHyAcACP(1)...
    + c_C12_FabA_BHyAcACP(end) - c_C12_FabA_BHyAcACP(1)...
    + c_C14_FabA_BHyAcACP(end) - c_C14_FabA_BHyAcACP(1)...
    + c_C16_FabA_BHyAcACP(end) - c_C16_FabA_BHyAcACP(1)...
    + c_C18_FabA_BHyAcACP(end) - c_C18_FabA_BHyAcACP(1)...
    + c_C20_FabA_BHyAcACP(end) - c_C20_FabA_BHyAcACP(1)...
    + c_C12_FabA_BHyAcACP_un(end) - c_C12_FabA_BHyAcACP_un(1)...
    + c_C14_FabA_BHyAcACP_un(end) - c_C14_FabA_BHyAcACP_un(1)...
    + c_C16_FabA_BHyAcACP_un(end) - c_C16_FabA_BHyAcACP_un(1)...
    + c_C18_FabA_BHyAcACP_un(end) - c_C18_FabA_BHyAcACP_un(1)...
    + c_C20_FabA_BHyAcACP_un(end) - c_C20_FabA_BHyAcACP_un(1)...
    + c_C4_FabA_EnAcACP(end) - c_C4_FabA_EnAcACP(1)...
    + c_C6_FabA_EnAcACP(end) - c_C6_FabA_EnAcACP(1)...
    + c_C8_FabA_EnAcACP(end) - c_C8_FabA_EnAcACP(1)...
    + c_C10_FabA_EnAcACP(end) - c_C10_FabA_EnAcACP(1)...
    + c_C12_FabA_EnAcACP(end) - c_C12_FabA_EnAcACP(1)...
    + c_C14_FabA_EnAcACP(end) - c_C14_FabA_EnAcACP(1)...
    + c_C16_FabA_EnAcACP(end) - c_C16_FabA_EnAcACP(1)...
    + c_C18_FabA_EnAcACP(end) - c_C18_FabA_EnAcACP(1)...
    + c_C20_FabA_EnAcACP(end) - c_C20_FabA_EnAcACP(1)...
    + c_C10_FabA_cis3EnAcACP(end) - c_C10_FabA_cis3EnAcACP(1)...
    + c_C12_FabA_EnAcACP_un(end) - c_C12_FabA_EnAcACP_un(1)...
    + c_C14_FabA_EnAcACP_un(end) - c_C14_FabA_EnAcACP_un(1)...
    + c_C16_FabA_EnAcACP_un(end) - c_C16_FabA_EnAcACP_un(1)...
    + c_C18_FabA_EnAcACP_un(end) - c_C18_FabA_EnAcACP_un(1)...
    + c_C20_FabA_EnAcACP_un(end) - c_C20_FabA_EnAcACP_un(1)...
    + c_FabA_ACP(end) - c_FabA_ACP(1);
    
    FabB = c_FabB(end) - c_FabB(1)...
    + c_C4_FabB_AcACP(end) - c_C4_FabB_AcACP(1)...
    + c_C6_FabB_AcACP(end) - c_C6_FabB_AcACP(1)...
    + c_C8_FabB_AcACP(end) - c_C8_FabB_AcACP(1)...
    + c_C10_FabB_AcACP(end) - c_C10_FabB_AcACP(1)...
    + c_C12_FabB_AcACP(end) - c_C12_FabB_AcACP(1)...
    + c_C14_FabB_AcACP(end) - c_C14_FabB_AcACP(1)...
    + c_C16_FabB_AcACP(end) - c_C16_FabB_AcACP(1)...
    + c_C18_FabB_AcACP(end) - c_C18_FabB_AcACP(1)...
    + c_C12_FabB_AcACP_un(end) - c_C12_FabB_AcACP_un(1)...
    + c_C14_FabB_AcACP_un(end) - c_C14_FabB_AcACP_un(1)...
    + c_C16_FabB_AcACP_un(end) - c_C16_FabB_AcACP_un(1)...
    + c_C18_FabB_AcACP_un(end) - c_C18_FabB_AcACP_un(1)...
    + c_C4_FabB_Act(end) - c_C4_FabB_Act(1)...
    + c_C6_FabB_Act(end) - c_C6_FabB_Act(1)...
    + c_C8_FabB_Act(end) - c_C8_FabB_Act(1)...
    + c_C10_FabB_Act(end) - c_C10_FabB_Act(1)...
    + c_C12_FabB_Act(end) - c_C12_FabB_Act(1)...
    + c_C14_FabB_Act(end) - c_C14_FabB_Act(1)...
    + c_C16_FabB_Act(end) - c_C16_FabB_Act(1)...
    + c_C18_FabB_Act(end) - c_C18_FabB_Act(1)...
    + c_C12_FabB_Act_un(end) - c_C12_FabB_Act_un(1)...
    + c_C14_FabB_Act_un(end) - c_C14_FabB_Act_un(1)...
    + c_C16_FabB_Act_un(end) - c_C16_FabB_Act_un(1)...
    + c_C18_FabB_Act_un(end) - c_C18_FabB_Act_un(1)...
    + c_C4_FabB_Act_MalACP(end) - c_C4_FabB_Act_MalACP(1)...
    + c_C6_FabB_Act_MalACP(end) - c_C6_FabB_Act_MalACP(1)...
    + c_C8_FabB_Act_MalACP(end) - c_C8_FabB_Act_MalACP(1)...
    + c_C10_FabB_Act_MalACP(end) - c_C10_FabB_Act_MalACP(1)...
    + c_C12_FabB_Act_MalACP(end) - c_C12_FabB_Act_MalACP(1)...
    + c_C14_FabB_Act_MalACP(end) - c_C14_FabB_Act_MalACP(1)...
    + c_C16_FabB_Act_MalACP(end) - c_C16_FabB_Act_MalACP(1)...
    + c_C18_FabB_Act_MalACP(end) - c_C18_FabB_Act_MalACP(1)...
    + c_C12_FabB_Act_MalACP_un(end) - c_C12_FabB_Act_MalACP_un(1)...
    + c_C14_FabB_Act_MalACP_un(end) - c_C14_FabB_Act_MalACP_un(1)...
    + c_C16_FabB_Act_MalACP_un(end) - c_C16_FabB_Act_MalACP_un(1)...
    + c_C18_FabB_Act_MalACP_un(end) - c_C18_FabB_Act_MalACP_un(1)...
    + c_C10_FabB_cis3EnAcACP(end) - c_C10_FabB_cis3EnAcACP(1)...
    + c_C10_FabB_Act_cis3(end) - c_C10_FabB_Act_cis3(1)...
    + c_C10_FabB_Act_cis3MalACP(end) - c_C10_FabB_Act_cis3MalACP(1)...
    + c_FabB_ACP(end) - c_FabB_ACP(1)...
    + c_FabB_AcCoA(end) - c_FabB_AcCoA(1)...
    + c_C2_FabB_Act(end) - c_C2_FabB_Act(1)...
    + c_C2_FabB_Act_MalACP(end) - c_C2_FabB_Act_MalACP(1)...
    + c_FabB_MalACP(end) - c_FabB_MalACP(1)...
    + c_C2_FabB_AcACP(end) - c_C2_FabB_AcACP(1);

Carbon = c_Bicarbonate(end)*1 - (c_Bicarbonate(1)*1)...
    + c_ACC_s2(end)*1 - (c_ACC_s2(1)*1)...
    + c_ACC_s3(end)*1 - (c_ACC_s3(1)*1)...
    + c_ACC_s4(end)*3 - (c_ACC_s4(1)*3)...
    + c_AcCoA(end)*2 - (c_AcCoA(1)*2)...
    + c_SucCoA(end)*4 - (c_SucCoA(1)*4)...
    + c_HexCoA(end)*6 - (c_HexCoA(1)*6)...
    + c_OcCoA(end)*8 - (c_OcCoA(1)*8)...
    + c_DecCoA(end)*10 - (c_DecCoA(1)*10)...
    + c_LauCoA(end)*12 - (c_LauCoA(1)*12)...
    + c_EthCoA(end)*14 - (c_EthCoA(1)*14)...
    + c_PalCoA(end)*16 - (c_PalCoA(1)*16)...
    + c_OcDecCoA(end)*18 - (c_OcDecCoA(1)*18)...
    + c_MalCoA(end)*3 - (c_MalCoA(1)*3)...
    + c_MalACP(end)*4 - (c_MalACP(1)*4)...
    + c_CO2(end)*1 - (c_CO2(1)*1)...
    + c_C4_BKeACP(end)*4 - (c_C4_BKeACP(1)*4)...
    + c_C6_BKeACP(end)*6 - (c_C6_BKeACP(1)*6)...
    + c_C8_BKeACP(end)*8 - (c_C8_BKeACP(1)*8)...
    + c_C10_BKeACP(end)*10 - (c_C10_BKeACP(1)*10)...
    + c_C12_BKeACP(end)*12 - (c_C12_BKeACP(1)*12)...
    + c_C14_BKeACP(end)*14 - (c_C14_BKeACP(1)*14)...
    + c_C16_BKeACP(end)*16 - (c_C16_BKeACP(1)*16)...
    + c_C18_BKeACP(end)*18 - (c_C18_BKeACP(1)*18)...
    + c_C20_BKeACP(end)*20 - (c_C20_BKeACP(1)*20)...
    + c_C12_BKeACP_un(end)*12 - (c_C12_BKeACP_un(1)*12)...
    + c_C14_BKeACP_un(end)*14 - (c_C14_BKeACP_un(1)*14)...
    + c_C16_BKeACP_un(end)*16 - (c_C16_BKeACP_un(1)*16)...
    + c_C18_BKeACP_un(end)*18 - (c_C18_BKeACP_un(1)*18)...
    + c_C20_BKeACP_un(end)*20 - (c_C20_BKeACP_un(1)*20)...
    + c_C4_BHyAcACP(end)*4 - (c_C4_BHyAcACP(1)*4)...
    + c_C6_BHyAcACP(end)*6 - (c_C6_BHyAcACP(1)*6)...
    + c_C8_BHyAcACP(end)*8 - (c_C8_BHyAcACP(1)*8)...
    + c_C10_BHyAcACP(end)*10 - (c_C10_BHyAcACP(1)*10)...
    + c_C12_BHyAcACP(end)*12 - (c_C12_BHyAcACP(1)*12)...
    + c_C14_BHyAcACP(end)*14 - (c_C14_BHyAcACP(1)*14)...
    + c_C16_BHyAcACP(end)*16 - (c_C16_BHyAcACP(1)*16)...
    + c_C18_BHyAcACP(end)*18 - (c_C18_BHyAcACP(1)*18)...
    + c_C20_BHyAcACP(end)*20 - (c_C20_BHyAcACP(1)*20)...
    + c_C12_BHyAcACP_un(end)*12 - (c_C12_BHyAcACP_un(1)*12)...
    + c_C14_BHyAcACP_un(end)*14 - (c_C14_BHyAcACP_un(1)*14)...
    + c_C16_BHyAcACP_un(end)*16 - (c_C16_BHyAcACP_un(1)*16)...
    + c_C18_BHyAcACP_un(end)*18 - (c_C18_BHyAcACP_un(1)*18)...
    + c_C20_BHyAcACP_un(end)*20 - (c_C20_BHyAcACP_un(1)*20)...
    + c_C4_EnAcACP(end)*4 - (c_C4_EnAcACP(1)*4)...
    + c_C6_EnAcACP(end)*6 - (c_C6_EnAcACP(1)*6)...
    + c_C8_EnAcACP(end)*8 - (c_C8_EnAcACP(1)*8)...
    + c_C10_EnAcACP(end)*10 - (c_C10_EnAcACP(1)*10)...
    + c_C12_EnAcACP(end)*12 - (c_C12_EnAcACP(1)*12)...
    + c_C14_EnAcACP(end)*14 - (c_C14_EnAcACP(1)*14)...
    + c_C16_EnAcACP(end)*16 - (c_C16_EnAcACP(1)*16)...
    + c_C18_EnAcACP(end)*18 - (c_C18_EnAcACP(1)*18)...
    + c_C20_EnAcACP(end)*20 - (c_C20_EnAcACP(1)*20)...
    + c_C10_cis3EnAcACP(end)*10 - (c_C10_cis3EnAcACP(1)*10)...
    + c_C12_EnAcACP_un(end)*12 - (c_C12_EnAcACP_un(1)*12)...
    + c_C14_EnAcACP_un(end)*14 - (c_C14_EnAcACP_un(1)*14)...
    + c_C16_EnAcACP_un(end)*16 - (c_C16_EnAcACP_un(1)*16)...
    + c_C18_EnAcACP_un(end)*18 - (c_C18_EnAcACP_un(1)*18)...
    + c_C20_EnAcACP_un(end)*20 - (c_C20_EnAcACP_un(1)*20)...
    + c_C4_AcACP(end)*4 - (c_C4_AcACP(1)*4)...
    + c_C6_AcACP(end)*6 - (c_C6_AcACP(1)*6)...
    + c_C8_AcACP(end)*8 - (c_C8_AcACP(1)*8)...
    + c_C10_AcACP(end)*10 - (c_C10_AcACP(1)*10)...
    + c_C12_AcACP(end)*12 - (c_C12_AcACP(1)*12)...
    + c_C14_AcACP(end)*14 - (c_C14_AcACP(1)*14)...
    + c_C16_AcACP(end)*16 - (c_C16_AcACP(1)*16)...
    + c_C18_AcACP(end)*18 - (c_C18_AcACP(1)*18)...
    + c_C20_AcACP(end)*20 - (c_C20_AcACP(1)*20)...
    + c_C12_AcACP_un(end)*12 - (c_C12_AcACP_un(1)*12)...
    + c_C14_AcACP_un(end)*14 - (c_C14_AcACP_un(1)*14)...
    + c_C16_AcACP_un(end)*16 - (c_C16_AcACP_un(1)*16)...
    + c_C18_AcACP_un(end)*18 - (c_C18_AcACP_un(1)*18)...
    + c_C20_AcACP_un(end)*20 - (c_C20_AcACP_un(1)*20)...
    + c_C4_FA(end)*4 - (c_C4_FA(1)*4)...
    + c_C6_FA(end)*6 - (c_C6_FA(1)*6)...
    + c_C8_FA(end)*8 - (c_C8_FA(1)*8)...
    + c_C10_FA(end)*10 - (c_C10_FA(1)*10)...
    + c_C12_FA(end)*12 - (c_C12_FA(1)*12)...
    + c_C14_FA(end)*14 - (c_C14_FA(1)*14)...
    + c_C16_FA(end)*16 - (c_C16_FA(1)*16)...
    + c_C18_FA(end)*18 - (c_C18_FA(1)*18)...
    + c_C20_FA(end)*20 - (c_C20_FA(1)*20)...
    + c_C12_FA_un(end)*12 - (c_C12_FA_un(1)*12)...
    + c_C14_FA_un(end)*14 - (c_C14_FA_un(1)*14)...
    + c_C16_FA_un(end)*16 - (c_C16_FA_un(1)*16)...
    + c_C18_FA_un(end)*18 - (c_C18_FA_un(1)*18)...
    + c_C20_FA_un(end)*20 - (c_C20_FA_un(1)*20)...
    + c_FabD_MalCoA(end)*3 - (c_FabD_MalCoA(1)*3)...
    + c_FabD_Act(end)*3 - (c_FabD_Act(1)*3)...
    + c_FabD_Act_ACP(end)*3 - (c_FabD_Act_ACP(1)*3)...
    + c_C2_FabH_CoA(end)*2 - (c_C2_FabH_CoA(1)*2)...
    + c_C4_FabH_CoA(end)*4 - (c_C4_FabH_CoA(1)*4)...
    + c_C6_FabH_CoA(end)*6 - (c_C6_FabH_CoA(1)*6)...
    + c_C8_FabH_CoA(end)*8 - (c_C8_FabH_CoA(1)*8)...
    + c_C10_FabH_CoA(end)*10 - (c_C10_FabH_CoA(1)*10)...
    + c_C12_FabH_CoA(end)*12 - (c_C12_FabH_CoA(1)*12)...
    + c_C14_FabH_CoA(end)*14 - (c_C14_FabH_CoA(1)*14)...
    + c_C16_FabH_CoA(end)*16 - (c_C16_FabH_CoA(1)*16)...
    + c_C18_FabH_CoA(end)*18 - (c_C18_FabH_CoA(1)*18)...
    + c_C2_FabH_Act(end)*2 - (c_C2_FabH_Act(1)*2)...
    + c_C4_FabH_Act(end)*4 - (c_C4_FabH_Act(1)*4)...
    + c_C6_FabH_Act(end)*6 - (c_C6_FabH_Act(1)*6)...
    + c_C8_FabH_Act(end)*8 - (c_C8_FabH_Act(1)*8)...
    + c_C10_FabH_Act(end)*10 - (c_C10_FabH_Act(1)*10)...
    + c_C12_FabH_Act(end)*12 - (c_C12_FabH_Act(1)*12)...
    + c_C14_FabH_Act(end)*14 - (c_C14_FabH_Act(1)*14)...
    + c_C16_FabH_Act(end)*16 - (c_C16_FabH_Act(1)*16)...
    + c_C18_FabH_Act(end)*18 - (c_C18_FabH_Act(1)*18)...
    + c_C2_FabH_Act_MalACP(end)*5 - (c_C2_FabH_Act_MalACP(1)*5)...
    + c_C4_FabH_Act_MalACP(end)*7 - (c_C4_FabH_Act_MalACP(1)*7)...
    + c_C6_FabH_Act_MalACP(end)*9 - (c_C6_FabH_Act_MalACP(1)*9)...
    + c_C8_FabH_Act_MalACP(end)*11 - (c_C8_FabH_Act_MalACP(1)*11)...
    + c_C10_FabH_Act_MalACP(end)*13 - (c_C10_FabH_Act_MalACP(1)*13)...
    + c_C12_FabH_Act_MalACP(end)*15 - (c_C12_FabH_Act_MalACP(1)*15)...
    + c_C14_FabH_Act_MalACP(end)*17 - (c_C14_FabH_Act_MalACP(1)*17)...
    + c_C16_FabH_Act_MalACP(end)*19 - (c_C16_FabH_Act_MalACP(1)*19)...
    + c_C18_FabH_Act_MalACP(end)*21 - (c_C18_FabH_Act_MalACP(1)*21)...
    + c_C4_FabG_NADPH_BKeACP(end)*4 - (c_C4_FabG_NADPH_BKeACP(1)*4)...
    + c_C6_FabG_NADPH_BKeACP(end)*6 - (c_C6_FabG_NADPH_BKeACP(1)*6)...
    + c_C8_FabG_NADPH_BKeACP(end)*8 - (c_C8_FabG_NADPH_BKeACP(1)*8)...
    + c_C10_FabG_NADPH_BKeACP(end)*10 - (c_C10_FabG_NADPH_BKeACP(1)*10)...
    + c_C12_FabG_NADPH_BKeACP(end)*12 - (c_C12_FabG_NADPH_BKeACP(1)*12)...
    + c_C14_FabG_NADPH_BKeACP(end)*14 - (c_C14_FabG_NADPH_BKeACP(1)*14)...
    + c_C16_FabG_NADPH_BKeACP(end)*16 - (c_C16_FabG_NADPH_BKeACP(1)*16)...
    + c_C18_FabG_NADPH_BKeACP(end)*18 - (c_C18_FabG_NADPH_BKeACP(1)*18)...
    + c_C20_FabG_NADPH_BKeACP(end)*20 - (c_C20_FabG_NADPH_BKeACP(1)*20)...
    + c_C12_FabG_NADPH_BKeACP_un(end)*12 - (c_C12_FabG_NADPH_BKeACP_un(1)*12)...
    + c_C14_FabG_NADPH_BKeACP_un(end)*14 - (c_C14_FabG_NADPH_BKeACP_un(1)*14)...
    + c_C16_FabG_NADPH_BKeACP_un(end)*16 - (c_C16_FabG_NADPH_BKeACP_un(1)*16)...
    + c_C18_FabG_NADPH_BKeACP_un(end)*18 - (c_C18_FabG_NADPH_BKeACP_un(1)*18)...
    + c_C20_FabG_NADPH_BKeACP_un(end)*20 - (c_C20_FabG_NADPH_BKeACP_un(1)*20)...
    + c_C4_FabZ_BHyAcACP(end)*4 - (c_C4_FabZ_BHyAcACP(1)*4)...
    + c_C6_FabZ_BHyAcACP(end)*6 - (c_C6_FabZ_BHyAcACP(1)*6)...
    + c_C8_FabZ_BHyAcACP(end)*8 - (c_C8_FabZ_BHyAcACP(1)*8)...
    + c_C10_FabZ_BHyAcACP(end)*10 - (c_C10_FabZ_BHyAcACP(1)*10)...
    + c_C12_FabZ_BHyAcACP(end)*12 - (c_C12_FabZ_BHyAcACP(1)*12)...
    + c_C14_FabZ_BHyAcACP(end)*14 - (c_C14_FabZ_BHyAcACP(1)*14)...
    + c_C16_FabZ_BHyAcACP(end)*16 - (c_C16_FabZ_BHyAcACP(1)*16)...
    + c_C18_FabZ_BHyAcACP(end)*18 - (c_C18_FabZ_BHyAcACP(1)*18)...
    + c_C20_FabZ_BHyAcACP(end)*20 - (c_C20_FabZ_BHyAcACP(1)*20)...
    + c_C12_FabZ_BHyAcACP_un(end)*12 - (c_C12_FabZ_BHyAcACP_un(1)*12)...
    + c_C14_FabZ_BHyAcACP_un(end)*14 - (c_C14_FabZ_BHyAcACP_un(1)*14)...
    + c_C16_FabZ_BHyAcACP_un(end)*16 - (c_C16_FabZ_BHyAcACP_un(1)*16)...
    + c_C18_FabZ_BHyAcACP_un(end)*18 - (c_C18_FabZ_BHyAcACP_un(1)*18)...
    + c_C20_FabZ_BHyAcACP_un(end)*20 - (c_C20_FabZ_BHyAcACP_un(1)*20)...
    + c_C4_FabZ_EnAcACP(end)*4 - (c_C4_FabZ_EnAcACP(1)*4)...
    + c_C6_FabZ_EnAcACP(end)*6 - (c_C6_FabZ_EnAcACP(1)*6)...
    + c_C8_FabZ_EnAcACP(end)*8 - (c_C8_FabZ_EnAcACP(1)*8)...
    + c_C10_FabZ_EnAcACP(end)*10 - (c_C10_FabZ_EnAcACP(1)*10)...
    + c_C12_FabZ_EnAcACP(end)*12 - (c_C12_FabZ_EnAcACP(1)*12)...
    + c_C14_FabZ_EnAcACP(end)*14 - (c_C14_FabZ_EnAcACP(1)*14)...
    + c_C16_FabZ_EnAcACP(end)*16 - (c_C16_FabZ_EnAcACP(1)*16)...
    + c_C18_FabZ_EnAcACP(end)*18 - (c_C18_FabZ_EnAcACP(1)*18)...
    + c_C20_FabZ_EnAcACP(end)*20 - (c_C20_FabZ_EnAcACP(1)*20)...
    + c_C12_FabZ_EnAcACP_un(end)*12 - (c_C12_FabZ_EnAcACP_un(1)*12)...
    + c_C14_FabZ_EnAcACP_un(end)*14 - (c_C14_FabZ_EnAcACP_un(1)*14)...
    + c_C16_FabZ_EnAcACP_un(end)*16 - (c_C16_FabZ_EnAcACP_un(1)*16)...
    + c_C18_FabZ_EnAcACP_un(end)*18 - (c_C18_FabZ_EnAcACP_un(1)*18)...
    + c_C20_FabZ_EnAcACP_un(end)*20 - (c_C20_FabZ_EnAcACP_un(1)*20)...
    + c_C4_FabA_BHyAcACP(end)*4 - (c_C4_FabA_BHyAcACP(1)*4)...
    + c_C6_FabA_BHyAcACP(end)*6 - (c_C6_FabA_BHyAcACP(1)*6)...
    + c_C8_FabA_BHyAcACP(end)*8 - (c_C8_FabA_BHyAcACP(1)*8)...
    + c_C10_FabA_BHyAcACP(end)*10 - (c_C10_FabA_BHyAcACP(1)*10)...
    + c_C12_FabA_BHyAcACP(end)*12 - (c_C12_FabA_BHyAcACP(1)*12)...
    + c_C14_FabA_BHyAcACP(end)*14 - (c_C14_FabA_BHyAcACP(1)*14)...
    + c_C16_FabA_BHyAcACP(end)*16 - (c_C16_FabA_BHyAcACP(1)*16)...
    + c_C18_FabA_BHyAcACP(end)*18 - (c_C18_FabA_BHyAcACP(1)*18)...
    + c_C20_FabA_BHyAcACP(end)*20 - (c_C20_FabA_BHyAcACP(1)*20)...
    + c_C12_FabA_BHyAcACP_un(end)*12 - (c_C12_FabA_BHyAcACP_un(1)*12)...
    + c_C14_FabA_BHyAcACP_un(end)*14 - (c_C14_FabA_BHyAcACP_un(1)*14)...
    + c_C16_FabA_BHyAcACP_un(end)*16 - (c_C16_FabA_BHyAcACP_un(1)*16)...
    + c_C18_FabA_BHyAcACP_un(end)*18 - (c_C18_FabA_BHyAcACP_un(1)*18)...
    + c_C20_FabA_BHyAcACP_un(end)*20 - (c_C20_FabA_BHyAcACP_un(1)*20)...
    + c_C4_FabA_EnAcACP(end)*4 - (c_C4_FabA_EnAcACP(1)*4)...
    + c_C6_FabA_EnAcACP(end)*6 - (c_C6_FabA_EnAcACP(1)*6)...
    + c_C8_FabA_EnAcACP(end)*8 - (c_C8_FabA_EnAcACP(1)*8)...
    + c_C10_FabA_EnAcACP(end)*10 - (c_C10_FabA_EnAcACP(1)*10)...
    + c_C12_FabA_EnAcACP(end)*12 - (c_C12_FabA_EnAcACP(1)*12)...
    + c_C14_FabA_EnAcACP(end)*14 - (c_C14_FabA_EnAcACP(1)*14)...
    + c_C16_FabA_EnAcACP(end)*16 - (c_C16_FabA_EnAcACP(1)*16)...
    + c_C18_FabA_EnAcACP(end)*18 - (c_C18_FabA_EnAcACP(1)*18)...
    + c_C20_FabA_EnAcACP(end)*20 - (c_C20_FabA_EnAcACP(1)*20)...
    + c_C10_FabA_cis3EnAcACP(end)*10 - (c_C10_FabA_cis3EnAcACP(1)*10)...
    + c_C12_FabA_EnAcACP_un(end)*12 - (c_C12_FabA_EnAcACP_un(1)*12)...
    + c_C14_FabA_EnAcACP_un(end)*14 - (c_C14_FabA_EnAcACP_un(1)*14)...
    + c_C16_FabA_EnAcACP_un(end)*16 - (c_C16_FabA_EnAcACP_un(1)*16)...
    + c_C18_FabA_EnAcACP_un(end)*18 - (c_C18_FabA_EnAcACP_un(1)*18)...
    + c_C20_FabA_EnAcACP_un(end)*20 - (c_C20_FabA_EnAcACP_un(1)*20)...
    + c_C4_FabI_NADH_EnAcACP(end)*4 - (c_C4_FabI_NADH_EnAcACP(1)*4)...
    + c_C6_FabI_NADH_EnAcACP(end)*6 - (c_C6_FabI_NADH_EnAcACP(1)*6)...
    + c_C8_FabI_NADH_EnAcACP(end)*8 - (c_C8_FabI_NADH_EnAcACP(1)*8)...
    + c_C10_FabI_NADH_EnAcACP(end)*10 - (c_C10_FabI_NADH_EnAcACP(1)*10)...
    + c_C12_FabI_NADH_EnAcACP(end)*12 - (c_C12_FabI_NADH_EnAcACP(1)*12)...
    + c_C14_FabI_NADH_EnAcACP(end)*14 - (c_C14_FabI_NADH_EnAcACP(1)*14)...
    + c_C16_FabI_NADH_EnAcACP(end)*16 - (c_C16_FabI_NADH_EnAcACP(1)*16)...
    + c_C18_FabI_NADH_EnAcACP(end)*18 - (c_C18_FabI_NADH_EnAcACP(1)*18)...
    + c_C20_FabI_NADH_EnAcACP(end)*20 - (c_C20_FabI_NADH_EnAcACP(1)*20)...
    + c_C12_FabI_NADH_EnAcACP_un(end)*12 - (c_C12_FabI_NADH_EnAcACP_un(1)*12)...
    + c_C14_FabI_NADH_EnAcACP_un(end)*14 - (c_C14_FabI_NADH_EnAcACP_un(1)*14)...
    + c_C16_FabI_NADH_EnAcACP_un(end)*16 - (c_C16_FabI_NADH_EnAcACP_un(1)*16)...
    + c_C18_FabI_NADH_EnAcACP_un(end)*18 - (c_C18_FabI_NADH_EnAcACP_un(1)*18)...
    + c_C20_FabI_NADH_EnAcACP_un(end)*20 - (c_C20_FabI_NADH_EnAcACP_un(1)*20)...
    + c_C4_TesA_AcACP(end)*4 - (c_C4_TesA_AcACP(1)*4)...
    + c_C6_TesA_AcACP(end)*6 - (c_C6_TesA_AcACP(1)*6)...
    + c_C8_TesA_AcACP(end)*8 - (c_C8_TesA_AcACP(1)*8)...
    + c_C10_TesA_AcACP(end)*10 - (c_C10_TesA_AcACP(1)*10)...
    + c_C12_TesA_AcACP(end)*12 - (c_C12_TesA_AcACP(1)*12)...
    + c_C14_TesA_AcACP(end)*14 - (c_C14_TesA_AcACP(1)*14)...
    + c_C16_TesA_AcACP(end)*16 - (c_C16_TesA_AcACP(1)*16)...
    + c_C18_TesA_AcACP(end)*18 - (c_C18_TesA_AcACP(1)*18)...
    + c_C20_TesA_AcACP(end)*20 - (c_C20_TesA_AcACP(1)*20)...
    + c_C12_TesA_AcACP_un(end)*12 - (c_C12_TesA_AcACP_un(1)*12)...
    + c_C14_TesA_AcACP_un(end)*14 - (c_C14_TesA_AcACP_un(1)*14)...
    + c_C16_TesA_AcACP_un(end)*16 - (c_C16_TesA_AcACP_un(1)*16)...
    + c_C18_TesA_AcACP_un(end)*18 - (c_C18_TesA_AcACP_un(1)*18)...
    + c_C20_TesA_AcACP_un(end)*20 - (c_C20_TesA_AcACP_un(1)*20)...
    + c_C4_FabF_AcACP(end)*4 - (c_C4_FabF_AcACP(1)*4)...
    + c_C6_FabF_AcACP(end)*6 - (c_C6_FabF_AcACP(1)*6)...
    + c_C8_FabF_AcACP(end)*8 - (c_C8_FabF_AcACP(1)*8)...
    + c_C10_FabF_AcACP(end)*10 - (c_C10_FabF_AcACP(1)*10)...
    + c_C12_FabF_AcACP(end)*12 - (c_C12_FabF_AcACP(1)*12)...
    + c_C14_FabF_AcACP(end)*14 - (c_C14_FabF_AcACP(1)*14)...
    + c_C16_FabF_AcACP(end)*16 - (c_C16_FabF_AcACP(1)*16)...
    + c_C18_FabF_AcACP(end)*18 - (c_C18_FabF_AcACP(1)*18)...
    + c_C12_FabF_AcACP_un(end)*12 - (c_C12_FabF_AcACP_un(1)*12)...
    + c_C14_FabF_AcACP_un(end)*14 - (c_C14_FabF_AcACP_un(1)*14)...
    + c_C16_FabF_AcACP_un(end)*16 - (c_C16_FabF_AcACP_un(1)*16)...
    + c_C18_FabF_AcACP_un(end)*18 - (c_C18_FabF_AcACP_un(1)*18)...
    + c_C4_FabF_Act(end)*4 - (c_C4_FabF_Act(1)*4)...
    + c_C6_FabF_Act(end)*6 - (c_C6_FabF_Act(1)*6)...
    + c_C8_FabF_Act(end)*8 - (c_C8_FabF_Act(1)*8)...
    + c_C10_FabF_Act(end)*10 - (c_C10_FabF_Act(1)*10)...
    + c_C12_FabF_Act(end)*12 - (c_C12_FabF_Act(1)*12)...
    + c_C14_FabF_Act(end)*14 - (c_C14_FabF_Act(1)*14)...
    + c_C16_FabF_Act(end)*16 - (c_C16_FabF_Act(1)*16)...
    + c_C18_FabF_Act(end)*18 - (c_C18_FabF_Act(1)*18)...
    + c_C12_FabF_Act_un(end)*12 - (c_C12_FabF_Act_un(1)*12)...
    + c_C14_FabF_Act_un(end)*14 - (c_C14_FabF_Act_un(1)*14)...
    + c_C16_FabF_Act_un(end)*16 - (c_C16_FabF_Act_un(1)*16)...
    + c_C18_FabF_Act_un(end)*18 - (c_C18_FabF_Act_un(1)*18)...
    + c_C4_FabF_Act_MalACP(end)*4 - (c_C4_FabF_Act_MalACP(1)*4)...
    + c_C6_FabF_Act_MalACP(end)*6 - (c_C6_FabF_Act_MalACP(1)*6)...
    + c_C8_FabF_Act_MalACP(end)*8 - (c_C8_FabF_Act_MalACP(1)*8)...
    + c_C10_FabF_Act_MalACP(end)*10 - (c_C10_FabF_Act_MalACP(1)*10)...
    + c_C12_FabF_Act_MalACP(end)*12 - (c_C12_FabF_Act_MalACP(1)*12)...
    + c_C14_FabF_Act_MalACP(end)*14 - (c_C14_FabF_Act_MalACP(1)*14)...
    + c_C16_FabF_Act_MalACP(end)*16 - (c_C16_FabF_Act_MalACP(1)*16)...
    + c_C18_FabF_Act_MalACP(end)*18 - (c_C18_FabF_Act_MalACP(1)*18)...
    + c_C12_FabF_Act_MalACP_un(end)*12 - (c_C12_FabF_Act_MalACP_un(1)*12)...
    + c_C14_FabF_Act_MalACP_un(end)*14 - (c_C14_FabF_Act_MalACP_un(1)*14)...
    + c_C16_FabF_Act_MalACP_un(end)*16 - (c_C16_FabF_Act_MalACP_un(1)*16)...
    + c_C18_FabF_Act_MalACP_un(end)*18 - (c_C18_FabF_Act_MalACP_un(1)*18)...
    + c_C4_FabB_AcACP(end)*4 - (c_C4_FabB_AcACP(1)*4)...
    + c_C6_FabB_AcACP(end)*6 - (c_C6_FabB_AcACP(1)*6)...
    + c_C8_FabB_AcACP(end)*8 - (c_C8_FabB_AcACP(1)*8)...
    + c_C10_FabB_AcACP(end)*10 - (c_C10_FabB_AcACP(1)*10)...
    + c_C12_FabB_AcACP(end)*12 - (c_C12_FabB_AcACP(1)*12)...
    + c_C14_FabB_AcACP(end)*14 - (c_C14_FabB_AcACP(1)*14)...
    + c_C16_FabB_AcACP(end)*16 - (c_C16_FabB_AcACP(1)*16)...
    + c_C18_FabB_AcACP(end)*18 - (c_C18_FabB_AcACP(1)*18)...
    + c_C12_FabB_AcACP_un(end)*12 - (c_C12_FabB_AcACP_un(1)*12)...
    + c_C14_FabB_AcACP_un(end)*14 - (c_C14_FabB_AcACP_un(1)*14)...
    + c_C16_FabB_AcACP_un(end)*16 - (c_C16_FabB_AcACP_un(1)*16)...
    + c_C18_FabB_AcACP_un(end)*18 - (c_C18_FabB_AcACP_un(1)*18)...
    + c_C4_FabB_Act(end)*4 - (c_C4_FabB_Act(1)*4)...
    + c_C6_FabB_Act(end)*6 - (c_C6_FabB_Act(1)*6)...
    + c_C8_FabB_Act(end)*8 - (c_C8_FabB_Act(1)*8)...
    + c_C10_FabB_Act(end)*10 - (c_C10_FabB_Act(1)*10)...
    + c_C12_FabB_Act(end)*12 - (c_C12_FabB_Act(1)*12)...
    + c_C14_FabB_Act(end)*14 - (c_C14_FabB_Act(1)*14)...
    + c_C16_FabB_Act(end)*16 - (c_C16_FabB_Act(1)*16)...
    + c_C18_FabB_Act(end)*18 - (c_C18_FabB_Act(1)*18)...
    + c_C12_FabB_Act_un(end)*12 - (c_C12_FabB_Act_un(1)*12)...
    + c_C14_FabB_Act_un(end)*14 - (c_C14_FabB_Act_un(1)*14)...
    + c_C16_FabB_Act_un(end)*16 - (c_C16_FabB_Act_un(1)*16)...
    + c_C18_FabB_Act_un(end)*18 - (c_C18_FabB_Act_un(1)*18)...
    + c_C4_FabB_Act_MalACP(end)*7 - (c_C4_FabB_Act_MalACP(1)*7)...
    + c_C6_FabB_Act_MalACP(end)*9 - (c_C6_FabB_Act_MalACP(1)*9)...
    + c_C8_FabB_Act_MalACP(end)*11 - (c_C8_FabB_Act_MalACP(1)*11)...
    + c_C10_FabB_Act_MalACP(end)*13 - (c_C10_FabB_Act_MalACP(1)*13)...
    + c_C12_FabB_Act_MalACP(end)*15 - (c_C12_FabB_Act_MalACP(1)*15)...
    + c_C14_FabB_Act_MalACP(end)*17 - (c_C14_FabB_Act_MalACP(1)*17)...
    + c_C16_FabB_Act_MalACP(end)*19 - (c_C16_FabB_Act_MalACP(1)*19)...
    + c_C18_FabB_Act_MalACP(end)*21 - (c_C18_FabB_Act_MalACP(1)*21)...
    + c_C12_FabB_Act_MalACP_un(end)*15 - (c_C12_FabB_Act_MalACP_un(1)*15)...
    + c_C14_FabB_Act_MalACP_un(end)*17 - (c_C14_FabB_Act_MalACP_un(1)*17)...
    + c_C16_FabB_Act_MalACP_un(end)*19 - (c_C16_FabB_Act_MalACP_un(1)*19)...
    + c_C18_FabB_Act_MalACP_un(end)*21 - (c_C18_FabB_Act_MalACP_un(1)*21)...
    + c_C10_FabB_cis3EnAcACP(end)*10 - (c_C10_FabB_cis3EnAcACP(1)*10)...
    + c_C10_FabB_Act_cis3(end)*10 - (c_C10_FabB_Act_cis3(1)*10)...
    + c_C10_FabB_Act_cis3MalACP(end)*13 - (c_C10_FabB_Act_cis3MalACP(1)*13)...
    + c_C4_FabH_AcACP(end)*6 - (c_C4_FabH_AcACP(1)*6)...
    + c_C6_FabH_AcACP(end)*8 - (c_C6_FabH_AcACP(1)*8)...
    + c_C8_FabH_AcACP(end)*10 - (c_C8_FabH_AcACP(1)*10)...
    + c_C10_FabH_AcACP(end)*12 - (c_C10_FabH_AcACP(1)*12)...
    + c_C12_FabH_AcACP(end)*14 - (c_C12_FabH_AcACP(1)*14)...
    + c_C14_FabH_AcACP(end)*16 - (c_C14_FabH_AcACP(1)*16)...
    + c_C16_FabH_AcACP(end)*18 - (c_C16_FabH_AcACP(1)*18)...
    + c_C18_FabH_AcACP(end)*20 - (c_C18_FabH_AcACP(1)*20)...
    + c_C20_FabH_AcACP(end)*22 - (c_C20_FabH_AcACP(1)*22)...
    + c_C12_FabH_AcACP_un(end)*14 - (c_C12_FabH_AcACP_un(1)*14)...
    + c_C14_FabH_AcACP_un(end)*16 - (c_C14_FabH_AcACP_un(1)*16)...
    + c_C16_FabH_AcACP_un(end)*18 - (c_C16_FabH_AcACP_un(1)*18)...
    + c_C18_FabH_AcACP_un(end)*20 - (c_C18_FabH_AcACP_un(1)*20)...
    + c_C20_FabH_AcACP_un(end)*22 - (c_C20_FabH_AcACP_un(1)*22)...
    + c_C4_FabH_Act_AcACP(end)*6 - (c_C4_FabH_Act_AcACP(1)*6)...
    + c_C6_FabH_Act_AcACP(end)*8 - (c_C6_FabH_Act_AcACP(1)*8)...
    + c_C8_FabH_Act_AcACP(end)*10 - (c_C8_FabH_Act_AcACP(1)*10)...
    + c_C10_FabH_Act_AcACP(end)*12 - (c_C10_FabH_Act_AcACP(1)*12)...
    + c_C12_FabH_Act_AcACP(end)*14 - (c_C12_FabH_Act_AcACP(1)*14)...
    + c_C14_FabH_Act_AcACP(end)*16 - (c_C14_FabH_Act_AcACP(1)*16)...
    + c_C16_FabH_Act_AcACP(end)*18 - (c_C16_FabH_Act_AcACP(1)*18)...
    + c_C18_FabH_Act_AcACP(end)*20 - (c_C18_FabH_Act_AcACP(1)*20)...
    + c_C20_FabH_Act_AcACP(end)*22 - (c_C20_FabH_Act_AcACP(1)*22)...
    + c_C12_FabH_Act_AcACP_un(end)*14 - (c_C12_FabH_Act_AcACP_un(1)*14)...
    + c_C14_FabH_Act_AcACP_un(end)*16 - (c_C14_FabH_Act_AcACP_un(1)*16)...
    + c_C16_FabH_Act_AcACP_un(end)*18 - (c_C16_FabH_Act_AcACP_un(1)*18)...
    + c_C18_FabH_Act_AcACP_un(end)*20 - (c_C18_FabH_Act_AcACP_un(1)*20)...
    + c_C20_FabH_Act_AcACP_un(end)*22 - (c_C20_FabH_Act_AcACP_un(1)*22)...
    + c_FabB_AcCoA(end)*2 - (c_FabB_AcCoA(1)*2)...
    + c_C2_FabB_Act(end)*2 - (c_C2_FabB_Act(1)*2)...
    + c_C2_FabB_Act_MalACP(end)*5 - (c_C2_FabB_Act_MalACP(1)*5)...
    + c_FabF_AcCoA(end)*2 - (c_FabF_AcCoA(1)*2)...
    + c_C2_FabF_Act(end)*2 - (c_C2_FabF_Act(1)*2)...
    + c_C2_FabF_Act_MalACP(end)*5 - (c_C2_FabF_Act_MalACP(1)*5)...
    + c_FabB_MalACP(end)*3 - (c_FabB_MalACP(1)*3)...
    + c_AcACP(end)*2 - (c_AcACP(1)*2)...
    + c_C2_FabB_AcACP(end)*2 - (c_C2_FabB_AcACP(1)*2)...
    + c_FabF_MalACP(end)*3 - (c_FabF_MalACP(1)*3)...
    + c_C2_FabF_AcACP(end)*2 - (c_C2_FabF_AcACP(1)*2);

check = [CoA,ACP,NADH,NADPH,ATP,ACC,FabD,FabH,FabG,FabZ,FabI,TesA,FabF,FabA,FabB,Carbon];

end